In [24]:
import geopandas as gpd
import pandas as pd
from project_paths import paths

In [25]:
aims = gpd.read_file(paths.aims_data / "aims.gpkg")
aims

,asset_id,asset_name,asset_sub_type,primary_purpose,alternative_purpose_1,alternative_purpose_2,asset_length,toe_level,protection_type,asset_maintainer,...,design_dcl,bank,effective_cl,effective_cl_dqf,include_in_flood_map,water_management_area,local_authority,frms_code,water_course_name,geometry
0,10,Not Available,Natural High Ground,Flood Risk Management,NaN,NaN,77.559998,NaN,Fluvial,"Private individual, Company or Charity",...,NaN,Left,NaN,NaN,Not Yet Considered,Wessex,Dorset,FR/13/S387,River Frome,"MULTILINESTRING ((363278.14 94625.53, 363262.8..."
1,100,Not Available,Natural High Ground,Flood Risk Management,NaN,NaN,65.769997,NaN,Fluvial,"Private individual, Company or Charity",...,NaN,Left,NaN,NaN,Not Yet Considered,Wessex,Dorset,FR/13/S412,River Asker,"MULTILINESTRING ((347350.2 92927.23, 347369.8 ..."
2,1000,Not Available,Natural High Ground,Flood Risk Management,NaN,NaN,156.280000,NaN,Fluvial,"Private individual, Company or Charity",...,NaN,Right,NaN,NaN,Not Yet Considered,Wessex,"Bournemouth, Christchurch and Poole",FR/13/S282,River Avon,"MULTILINESTRING ((414064.24 98893.53, 414032.3..."
3,10000,Not Available,Natural High Ground,Flood Risk Management,NaN,NaN,11.310000,NaN,Fluvial,"Private individual, Company or Charity",...,NaN,Left,NaN,NaN,Considered and Rejected,Yorkshire,Kirklees,FR/08/S658,River Dearne,"MULTILINESTRING ((424639.79 409988.03, 424628...."
4,100002,Not Available,Natural High Ground,Flood Risk Management,NaN,NaN,467.100010,NaN,Fluvial,"Private individual, Company or Charity",...,NaN,Right,NaN,NaN,Considered and Rejected,Wessex,North Somerset,FR/14/S100,Land Yeo,"MULTILINESTRING ((340535.23 171088.47, 340512...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141991,99985,Not Available,Embankment,Flood Risk Management,NaN,NaN,231.460010,NaN,Fluvial,"Private individual, Company or Charity",...,NaN,Right,91.07,crest_level_dqf_1,Considered and Rejected,Cumbria and Lancashire,South Lakeland,FR/09/S099,Great Langdale Beck,"MULTILINESTRING ((329363.82 506093.59, 329268...."
141992,99990,Not Available,Natural High Ground,Flood Risk Management,NaN,NaN,153.050000,NaN,Fluvial,"Private individual, Company or Charity",...,NaN,Right,NaN,NaN,Considered and Rejected,Wessex,North Somerset,FR/14/S010,Cross Rhyne,"MULTILINESTRING ((332827.83 159144.77, 332847...."
141993,99991,Not Available,Natural High Ground,Flood Risk Management,NaN,NaN,154.750000,NaN,Fluvial,"Private individual, Company or Charity",...,NaN,Left,NaN,NaN,Considered and Rejected,Wessex,North Somerset,FR/14/S010,Cross Rhyne,"MULTILINESTRING ((332829.81 159139.4, 332834.6..."
141994,99992,Not Available,Natural High Ground,Flood Risk Management,NaN,NaN,342.660000,NaN,Fluvial,"Private individual, Company or Charity",...,NaN,Left,NaN,NaN,Not Yet Considered,Hertfordshire and North London,Welwyn Hatfield,FR/17/S027,River Lea or Lee,"MULTILINESTRING ((522572.99 211448.21, 522549...."
141995,99995,Not Available,Embankment,Flood Risk Management,NaN,NaN,95.110001,NaN,Fluvial/Tidal,Environment Agency,...,NaN,Right,7.19,crest_level_dqf_1,Considered and Rejected,Cumbria and Lancashire,South Lakeland,FR/09/S108,River Gilpin,"MULTILINESTRING ((346676.87 487905.31, 346673...."

In [26]:
aims.crs

<Projected CRS: EPSG:27700>
Name: OSGB36 / British National Grid
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: United Kingdom (UK) - offshore to boundary of UKCS within 49°45'N to 61°N and 9°W to 2°E; onshore Great Britain (England, Wales and Scotland). Isle of Man onshore.
- bounds: (-9.01, 49.75, 2.01, 61.01)
Coordinate Operation:
- name: British National Grid
- method: Transverse Mercator
Datum: Ordnance Survey of Great Britain 1936
- Ellipsoid: Airy 1830
- Prime Meridian: Greenwich

In [27]:
centroids_df = gpd.GeoDataFrame(aims["asset_id"], geometry=aims.geometry.centroid, crs=aims.crs)
centroids_df

       asset_id                       geometry
0            10   POINT (363244.258 94642.589)
1           100   POINT (347376.191 92947.314)
2          1000   POINT (414034.541 98965.406)
3         10000    POINT (424634.14 409988.33)
4        100002  POINT (340401.839 170970.115)
...         ...                            ...
141991    99985  POINT (329259.644 506052.335)
141992    99990  POINT (332890.139 159185.737)
141993    99991  POINT (332892.787 159179.196)
141994    99992  POINT (522517.344 211601.944)
141995    99995  POINT (346643.627 487937.728)

[141996 rows x 2 columns]

In [28]:
eir_df = pd.read_csv(paths.ea_data / "ea_eir_data.csv")
eir_df

,Asset AIMS ID,Completion Date,Calculated Condition,Asset FCRM Target Condition,BRC,Year Last Refurbished,Repair Deadline Date,Agreed by Designated Engineer,Asset Year Last Refurbished
0,10,28/09/2009,888.0,888,888,888.0,888,888,888.0
1,100,NaN,888.0,888,888,888.0,888,888,888.0
2,100,09/08/2018,888.0,888,888,888.0,888,888,888.0
3,100,02/08/2019,888.0,888,888,888.0,888,888,888.0
4,100,20/10/2020,888.0,888,888,888.0,888,888,888.0
...,...,...,...,...,...,...,...,...,...
1037159,99999,31/10/2018,888.0,888,888,888.0,888,888,888.0
1037160,99999,26/10/2020,888.0,888,888,888.0,888,888,888.0
1037161,99999,04/10/2021,888.0,888,888,888.0,888,888,888.0
1037162,99999,30/10/2022,888.0,888,888,888.0,888,888,888.0
1037163,99999,03/12/2024,888.0,888,888,888.0,888,888,888.0

In [29]:
print(len(eir_df["Asset AIMS ID"].unique()))
print(len(eir_df["Asset AIMS ID"]))

170329
1037164

In [30]:
import numpy as np

def convert(series: pd.Series) -> pd.Series:
    num = pd.to_numeric(series, errors="coerce")
    num_cleaned = num.where(~num.isin([888, 999]), other=np.nan)
    return num_cleaned

In [31]:
eir_df["Year Last Refurbished"] = convert(eir_df["Year Last Refurbished"])
eir_df["Asset Year Last Refurbished"] = convert(eir_df["Asset Year Last Refurbished"])

In [32]:
print(eir_df[["Asset AIMS ID", "Year Last Refurbished", "Asset Year Last Refurbished"]].describe())
print()
print(eir_df[["Asset AIMS ID", "Year Last Refurbished", "Asset Year Last Refurbished"]].info())

       Asset AIMS ID  Year Last Refurbished  Asset Year Last Refurbished
count   1.037164e+06             739.000000                   639.000000
mean    1.342191e+05            2011.047361                  2010.555556
std     1.355894e+05               6.900114                     7.162881
min     2.000000e+00            1994.000000                  1994.000000
25%     4.612300e+04            2012.000000                  2006.000000
50%     1.054460e+05            2013.000000                  2013.000000
75%     1.567400e+05            2015.000000                  2014.000000
max     7.979800e+05            2020.000000                  2020.000000

<class 'pandas.DataFrame'>
RangeIndex: 1037164 entries, 0 to 1037163
Data columns (total 3 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   Asset AIMS ID                1037164 non-null  int64
 1   Year Last Refurbished        739 non-null      float64
 2   Asset Year Last Refurbished  639 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 23.7 MB
None

In [33]:
both_but_different = eir_df[eir_df["Year Last Refurbished"].notna() & eir_df["Asset Year Last Refurbished"] & (eir_df["Year Last Refurbished"] != eir_df["Asset Year Last Refurbished"])]
both_but_different

Empty DataFrame
Columns: [Asset AIMS ID, Completion Date, Calculated Condition, Asset FCRM Target Condition, BRC, Year Last Refurbished, Repair Deadline Date, Agreed by Designated Engineer, Asset Year Last Refurbished]
Index: []

good

In [34]:
only_year = eir_df[eir_df["Year Last Refurbished"].notna() & eir_df["Asset Year Last Refurbished"].isna()]

only_asset_year = eir_df[eir_df["Year Last Refurbished"].isna() & eir_df["Asset Year Last Refurbished"].notna()]

print(len(only_year))
print(len(only_asset_year))

100
0

In [35]:
eir_df["raw Calculated Condition"] = eir_df["Calculated Condition"]
eir_df["Calculated Condition"] = convert(eir_df["Calculated Condition"])

print(len(eir_df[eir_df["raw Calculated Condition"].eq(888)]))
print(len(eir_df[eir_df["raw Calculated Condition"].eq(999)]))
print(len(eir_df[eir_df["raw Calculated Condition"].isin([0,1,2,3,4,5])]))
print(len(eir_df[eir_df["raw Calculated Condition"].isna()]))

print(len(eir_df[eir_df["Calculated Condition"].isna()]))      
print(len(eir_df[eir_df["Calculated Condition"].notna()]))

706946
22487
275571
32160
761593
275571

todo - EA say in response that the redaction is by asset, so there should be no asset ids where there is both an na and notna condition grade.

In [36]:
eir_clean_df = eir_df[eir_df["Calculated Condition"].notna()].copy()
eir_clean_df.shape

(275571, 10)

In [37]:
# currently the eir data has multiple entries per asset for multiple inspections
# so currently longitudinal.
# this will be useful for later, but for now i want a cross sectional dataset for the first steps

eir_clean_df["inspection_date"] = pd.to_datetime(eir_clean_df["Completion Date"], errors="coerce", format="%d/%m/%Y")
print(eir_clean_df.head())
print()
print(eir_clean_df["inspection_date"].isna().sum())

    Asset AIMS ID Completion Date  Calculated Condition  \
37         100006      08/06/2018                   3.0
38         100006      23/08/2018                   3.0
39         100006      26/02/2019                   3.0
40         100006      06/09/2019                   3.0
41         100006      25/06/2020                   3.0

   Asset FCRM Target Condition  BRC  Year Last Refurbished  \
37                    3 - Fair  NaN                    NaN
38                    3 - Fair  NaN                    NaN
39                    3 - Fair  NaN                    NaN
40                    3 - Fair  NaN                    NaN
41                    3 - Fair  NaN                    NaN

   Repair Deadline Date Agreed by Designated Engineer  \
37                  NaN                           NaN
38                  NaN                           NaN
39                  NaN                           NaN
40                  NaN                           NaN
41                  NaN                           NaN

    Asset Year Last Refurbished  raw Calculated Condition inspection_date
37                          NaN                       3.0      2018-06-08
38                          NaN                       3.0      2018-08-23
39                          NaN                       3.0      2019-02-26
40                          NaN                       3.0      2019-09-06
41                          NaN                       3.0      2020-06-25

2337

In [38]:
print(eir_clean_df[eir_clean_df["inspection_date"].isna()])

         Asset AIMS ID Completion Date  Calculated Condition  \
15198           103168             NaN                   0.0
15657           103248             NaN                   0.0
16065           103332             NaN                   0.0
17815           103675             NaN                   0.0
17824           103676             NaN                   0.0
...                ...             ...                   ...
1033410          99235             NaN                   0.0
1034196          99384             NaN                   0.0
1034486          99459             NaN                   0.0
1035186          99605             NaN                   0.0
1036172          99770             NaN                   0.0

        Asset FCRM Target Condition  BRC  Year Last Refurbished  \
15198                      3 - Fair  NaN                    NaN
15657                      3 - Fair  NaN                    NaN
16065                      3 - Fair  NaN                    NaN
17815                      3 - Fair  NaN                    NaN
17824                      3 - Fair  NaN                    NaN
...                             ...  ...                    ...
1033410                    3 - Fair  NaN                    NaN
1034196                    3 - Fair  NaN                    NaN
1034486                    3 - Fair  NaN                    NaN
1035186                    3 - Fair  NaN                    NaN
1036172                    3 - Fair  NaN                    NaN

        Repair Deadline Date Agreed by Designated Engineer  \
15198                    NaN                           NaN
15657                    NaN                           NaN
16065                    NaN                           NaN
17815                    NaN                           NaN
17824                    NaN                           NaN
...                      ...                           ...
1033410                  NaN                           NaN
1034196                  NaN                           NaN
1034486                  NaN                           NaN
1035186                  NaN                           NaN
1036172                  NaN                           NaN

         Asset Year Last Refurbished  raw Calculated Condition inspection_date
15198                            NaN                       0.0             NaT
15657                            NaN                       0.0             NaT
16065                            NaN                       0.0             NaT
17815                            NaN                       0.0             NaT
17824                            NaN                       0.0             NaT
...                              ...                       ...             ...
1033410                          NaN                       0.0             NaT
1034196                          NaN                       0.0             NaT
1034486                          NaN                       0.0             NaT
1035186                          NaN                       0.0             NaT
1036172                          NaN                       0.0             NaT

[2337 rows x 11 columns]

it ought to be impossible to have a grade without an inspection date?

In [39]:
print(eir_clean_df[eir_clean_df["inspection_date"].isna()][["Asset AIMS ID", "Calculated Condition"]].groupby("Calculated Condition").count())

                      Asset AIMS ID
Calculated Condition
0.0                            2248
1.0                               2
2.0                              28
3.0                              46
4.0                              12
5.0                               1

decision point - should drop these rows?

In [40]:
eir_cs = (
    eir_clean_df
    .sort_values(by = "inspection_date", ascending=False, na_position="last")
    .drop_duplicates(subset="Asset AIMS ID", keep="first")
)

print(eir_cs.info())
print()
print(eir_cs.describe())
print()
print(eir_cs.head())

<class 'pandas.DataFrame'>
Index: 36562 entries, 907310 to 930297
Data columns (total 11 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Asset AIMS ID                  36562 non-null  int64
 1   Completion Date                36554 non-null  str
 2   Calculated Condition           36562 non-null  float64
 3   Asset FCRM Target Condition    36502 non-null  str
 4   BRC                            2151 non-null   str
 5   Year Last Refurbished          52 non-null     float64
 6   Repair Deadline Date           1293 non-null   str
 7   Agreed by Designated Engineer  1539 non-null   str
 8   Asset Year Last Refurbished    43 non-null     float64
 9   raw Calculated Condition       36562 non-null  float64
 10  inspection_date                36554 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(4), int64(1), str(5)
memory usage: 3.3 MB
None

       Asset AIMS ID  Calculated Condition  Year Last Refurbished  \
count   36562.000000          36562.000000              52.000000
mean   176417.592117              2.853427            2011.192308
min         4.000000              0.000000            1994.000000
25%     51726.750000              3.000000            2011.250000
50%    122209.500000              3.000000            2013.000000
75%    176692.500000              3.000000            2015.000000
max    797527.000000              5.000000            2020.000000
std    181332.564084              0.660115               7.076718

       Asset Year Last Refurbished  raw Calculated Condition  \
count                    43.000000              36562.000000
mean                   2010.511628                  2.853427
min                    1994.000000                  0.000000
25%                    2009.000000                  3.000000
50%                    2013.000000                  3.000000
75%                    2014.000000                  3.000000
max                    2020.000000                  5.000000
std                       7.414182                  0.660115

                  inspection_date
count                       36554
mean   2024-12-07 16:02:32.847841
min           1996-08-12 00:00:00
25%           2024-11-29 00:00:00
50%           2025-07-17 00:00:00
75%           2025-11-06 00:00:00
max           2026-03-04 00:00:00
std                           NaN

        Asset AIMS ID Completion Date  Calculated Condition  \
907310         758782      04/03/2026                   3.0
907369         758843      04/03/2026                   1.0
907318         758784      04/03/2026                   2.0
906857         757948      04/03/2026                   1.0
907540         758996      04/03/2026                   1.0

       Asset FCRM Target Condition  BRC  Year Last Refurbished  \
907310                    3 - Fair  NaN                    NaN
907369                    3 - Fair  NaN                    NaN
907318                    3 - Fair  NaN                    NaN
906857                    3 - Fair  NaN                    NaN
907540                    3 - Fair  NaN                    NaN

       Repair Deadline Date Agreed by Designated Engineer  \
907310                  NaN                           NaN
907369                  NaN                           NaN
907318                  NaN                           NaN
906857                  NaN                           NaN
907540                  NaN                           NaN

        Asset Year Last Refurbished  raw Calculated Condition inspection_date
907310                          NaN                       3.0      2026-03-04
907369                          NaN                       1.0      2026-03-04
907318                          NaN                       2.0      2026-03-04
906857                          NaN                       1.0      2026-03-04
907540                          NaN                       1.0      2026-03-04

distribution of grades looks extremely unbalanced

In [41]:
eir_cs = eir_cs.rename({
    "Asset AIMS ID": "asset_id",
    "Completion Date": "eir_completion_date",
    "Calculated Condition": "eir_condition_grade",
    "Asset FCRM Target Condition": "eir_asset_target_condition",
    "BRC": "eir_below_required_condition",
    "Year Last Refurbished": "eir_year_last_refurbished",
    "Repair Deadline Date": "eir_repair_deadline",
    "Agreed by Designated Engineer": "eir_agreed_by_engineer",
    "Asset Year Last Refurbished": "eir_asset_year_last_refurbished",
    "raw Calculated Condition": "eir_raw_calculated_condition",
    "inspection_date": "eir_inspection_date",
}, axis="columns")

print(eir_cs.columns)

eir_cs = eir_cs[
    [
        "asset_id",
        "eir_inspection_date",
        "eir_condition_grade",
        "eir_asset_target_condition",
        "eir_below_required_condition",
        "eir_year_last_refurbished",
        "eir_repair_deadline",
        "eir_agreed_by_engineer",
    ]
]


eir_cs

Index(['asset_id', 'eir_completion_date', 'eir_condition_grade',
       'eir_asset_target_condition', 'eir_below_required_condition',
       'eir_year_last_refurbished', 'eir_repair_deadline',
       'eir_agreed_by_engineer', 'eir_asset_year_last_refurbished',
       'eir_raw_calculated_condition', 'eir_inspection_date'],
      dtype='str')

,asset_id,eir_inspection_date,eir_condition_grade,eir_asset_target_condition,eir_below_required_condition,eir_year_last_refurbished,eir_repair_deadline,eir_agreed_by_engineer
907310,758782,2026-03-04,3.0,3 - Fair,NaN,NaN,NaN,NaN
907369,758843,2026-03-04,1.0,3 - Fair,NaN,NaN,NaN,NaN
907318,758784,2026-03-04,2.0,3 - Fair,NaN,NaN,NaN,NaN
906857,757948,2026-03-04,1.0,3 - Fair,NaN,NaN,NaN,NaN
907540,758996,2026-03-04,1.0,3 - Fair,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
927130,791491,NaT,0.0,3 - Fair,NaN,NaN,NaN,NaN
927133,791494,NaT,0.0,3 - Fair,NaN,NaN,NaN,NaN
927250,791667,NaT,3.0,3 - Fair,NaN,NaN,NaN,NaN
927410,791886,NaT,0.0,3 - Fair,NaN,NaN,NaN,NaN
930297,797140,NaT,0.0,NaN,NaN,NaN,NaN,NaN

In [42]:
eir_cs_clean = eir_cs.copy()

target_condition_map = {
    str(grade).split(" - ")[0]: str(grade).split(" - ")[1]
    for grade in eir_cs_clean["eir_asset_target_condition"].unique().tolist()
    if grade is not np.nan and len(str(grade).split(" - ")) == 2
}

print(target_condition_map)

{'3': 'Fair', '2': 'Good', '4': 'Poor', '1': 'Very Good', '0': 'Unchecked', '5': 'Very Poor'}

In [43]:

eir_cs_clean["eir_asset_target_condition"] =  list(map(lambda x: str(x).split(" - ")[0], eir_cs_clean["eir_asset_target_condition"]))

eir_cs_clean

,asset_id,eir_inspection_date,eir_condition_grade,eir_asset_target_condition,eir_below_required_condition,eir_year_last_refurbished,eir_repair_deadline,eir_agreed_by_engineer
907310,758782,2026-03-04,3.0,3,NaN,NaN,NaN,NaN
907369,758843,2026-03-04,1.0,3,NaN,NaN,NaN,NaN
907318,758784,2026-03-04,2.0,3,NaN,NaN,NaN,NaN
906857,757948,2026-03-04,1.0,3,NaN,NaN,NaN,NaN
907540,758996,2026-03-04,1.0,3,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
927130,791491,NaT,0.0,3,NaN,NaN,NaN,NaN
927133,791494,NaT,0.0,3,NaN,NaN,NaN,NaN
927250,791667,NaT,3.0,3,NaN,NaN,NaN,NaN
927410,791886,NaT,0.0,3,NaN,NaN,NaN,NaN
930297,797140,NaT,0.0,nan,NaN,NaN,NaN,NaN

In [44]:
# joined_aims_eir = pd.DataFrame.join(aims, eir_cs_clean, on="asset_id", how="inner", validate="1:1")
# above - mismatched types - asset id is numeric in one df and string in another.
# should have a cell that specifies the schema of each df explicitly, like the naming one for eir

joined_aims_eir = pd.concat([aims.set_index("asset_id"), eir_cs_clean.set_index("asset_id")], axis=1, join="outer", verify_integrity=True)

print(joined_aims_eir.head())
print()
print(joined_aims_eir.info())
print()
print(joined_aims_eir.describe())

             asset_name       asset_sub_type        primary_purpose  \
asset_id
10        Not Available  Natural High Ground  Flood Risk Management
100       Not Available  Natural High Ground  Flood Risk Management
1000      Not Available  Natural High Ground  Flood Risk Management
10000     Not Available  Natural High Ground  Flood Risk Management
100002    Not Available  Natural High Ground  Flood Risk Management

         alternative_purpose_1 alternative_purpose_2  asset_length  toe_level  \
asset_id
10                         NaN                   NaN     77.559998        NaN
100                        NaN                   NaN     65.769997        NaN
1000                       NaN                   NaN    156.280000        NaN
10000                      NaN                   NaN     11.310000        NaN
100002                     NaN                   NaN    467.100010        NaN

         protection_type                        asset_maintainer  \
asset_id
10               Fluvial  Private individual, Company or Charity
100              Fluvial  Private individual, Company or Charity
1000             Fluvial  Private individual, Company or Charity
10000            Fluvial  Private individual, Company or Charity
100002           Fluvial  Private individual, Company or Charity

         asset_operator  ...   frms_code water_course_name  \
asset_id                 ...
10              Unknown  ...  FR/13/S387       River Frome
100             Unknown  ...  FR/13/S412       River Asker
1000            Unknown  ...  FR/13/S282        River Avon
10000           Unknown  ...  FR/08/S658      River Dearne
100002          Unknown  ...  FR/14/S100          Land Yeo

                                                   geometry  \
asset_id
10        MULTILINESTRING ((363278.14 94625.53, 363262.8...
100       MULTILINESTRING ((347350.2 92927.23, 347369.8 ...
1000      MULTILINESTRING ((414064.24 98893.53, 414032.3...
10000     MULTILINESTRING ((424639.79 409988.03, 424628....
100002    MULTILINESTRING ((340535.23 171088.47, 340512....

          eir_inspection_date eir_condition_grade  eir_asset_target_condition  \
asset_id
10                        NaT                 NaN                         NaN
100                       NaT                 NaN                         NaN
1000                      NaT                 NaN                         NaN
10000                     NaT                 NaN                         NaN
100002                    NaT                 NaN                         NaN

         eir_below_required_condition  eir_year_last_refurbished  \
asset_id
10                                NaN                        NaN
100                               NaN                        NaN
1000                              NaN                        NaN
10000                             NaN                        NaN
100002                            NaN                        NaN

          eir_repair_deadline eir_agreed_by_engineer
asset_id
10                        NaN                    NaN
100                       NaN                    NaN
1000                      NaN                    NaN
10000                     NaN                    NaN
100002                    NaN                    NaN

[5 rows x 43 columns]

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 178558 entries, 10 to 797140
Data columns (total 43 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   asset_name                    141996 non-null  str
 1   asset_sub_type                141996 non-null  str
 2   primary_purpose               141996 non-null  str
 3   alternative_purpose_1         8107 non-null    str
 4   alternative_purpose_2         2817 non-null    str
 5   asset_length                  141993 non-null  float64
 6   toe_level                     2660 non-null    float64
 7   protection_type               141359 non-null  str
 8   asset_maintainer              141996 non-null  str
 9   asset_operator                141996 non-null  str
 10  asset_owner                   141996 non-null  str
 11  current_condition             141958 non-null  str
 12  target_condition              141872 non-null  str
 13  current_sop                   4696 non-null    float64
 14  current_sop_date              3352 non-null    str
 15  design_sop                    116479 non-null  float64
 16  design_sop_dqf                2201 non-null    str
 17  design_ucl                    11055 non-null   float64
 18  year_last_refurbished         1038 non-null    float64
 19  last_inspection_date          129052 non-null  str
 20  next_inspection_date          102301 non-null  str
 21  asset_start_date              32889 non-null   str
 22  actual_dcl                    74670 non-null   float64
 23  actual_dcl_dqf                73357 non-null   str
 24  actual_ucl                    74492 non-null   float64
 25  actual_ucl_dqf                73062 non-null   str
 26  design_dcl                    12572 non-null   float64
 27  bank                          135226 non-null  str
 28  effective_cl                  20092 non-null   float64
 29  effective_cl_dqf              19071 non-null   str
 30  include_in_flood_map          140151 non-null  str
 31  water_management_area         141996 non-null  str
 32  local_authority               141996 non-null  str
 33  frms_code                     141996 non-null  str
 34  water_course_name             141996 non-null  str
 35  geometry                      141996 non-null  geometry
 36  eir_inspection_date           36554 non-null   datetime64[us]
 37  eir_condition_grade           36562 non-null   float64
 38  eir_asset_target_condition    36562 non-null   str
 39  eir_below_required_condition  2151 non-null    str
 40  eir_year_last_refurbished     52 non-null      float64
 41  eir_repair_deadline           1293 non-null    str
 42  eir_agreed_by_engineer        1539 non-null    str
dtypes: datetime64[us](1), float64(12), geometry(1), str(29)
memory usage: 59.9+ MB
None

        asset_length    toe_level   current_sop     design_sop    design_ucl  \
count  141993.000000  2660.000000   4696.000000  116479.000000  11055.000000
mean      414.089448     4.099453    286.174830      76.547549     22.917466
min         0.010000    -3.000000      0.000000       0.000000      0.000000
25%        41.869999     1.842250     50.000000       5.000000      5.280000
50%       144.230000     2.851000    100.000000       5.000000      6.900000
75%       441.500000     4.300000    200.000000      50.000000     26.000000
max     24196.820000   223.000000  10000.000000    9999.000000    276.399990
std       793.500401     9.080826    623.906862     228.633890     35.482221

       year_last_refurbished    actual_dcl    actual_ucl    design_dcl  \
count            1038.000000  74670.000000  74492.000000  12572.000000
mean             2012.736994     39.876478     40.033323     24.667833
min              1948.000000     -1.000000     -1.000000  -9999.000000
25%              2011.000000      6.080000      6.160000      5.230000
50%              2014.000000     19.837499     20.100000      6.800000
75%              2017.000000     57.150002     57.641749     26.680000
max              2024.000000    297.609990    292.260010  18900.000000
std                 7.330285     47.797064     47.560088    194.061702

       effective_cl         eir_inspection_date  eir_condition_grade  \
count  20092.000000                       36554         36562.000000
mean      19.286604  2024-12-07 16:02:32.847841             2.853427
min       -0.200000         1996-08-12 00:00:00             0.000000
25%        4.260000         2024-11-29 00:00:00             3.000000
50%        6.380000         2025-07-17 00:00:00             3.000000
75%       20.020250         2025-11-06 00:00:00             3.000000
max      284.954990         2026-03-04 00:00:00             5.000000
std       28.793228                         NaN             0.660115

       eir_year_last_refurbished
count                  52.000000
mean                 2011.192308
min                  1994.000000
25%                  2011.250000
50%                  2013.000000
75%                  2015.000000
max                  2020.000000
std                     7.076718

In [45]:
condition_coverage_check = joined_aims_eir[
    (joined_aims_eir["current_condition"].isin([" ", "", "\t"]) | joined_aims_eir["current_condition"].isna()) & joined_aims_eir["eir_condition_grade"].notna()
]

condition_coverage_check

,asset_name,asset_sub_type,primary_purpose,alternative_purpose_1,alternative_purpose_2,asset_length,toe_level,protection_type,asset_maintainer,asset_operator,...,frms_code,water_course_name,geometry,eir_inspection_date,eir_condition_grade,eir_asset_target_condition,eir_below_required_condition,eir_year_last_refurbished,eir_repair_deadline,eir_agreed_by_engineer
asset_id,,,,,,,,,,,,,,,,,,,,,
758782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,2026-03-04,3.0,3,NaN,NaN,NaN,NaN
758843,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,2026-03-04,1.0,3,NaN,NaN,NaN,NaN
758784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,2026-03-04,2.0,3,NaN,NaN,NaN,NaN
757948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,2026-03-04,1.0,3,NaN,NaN,NaN,NaN
758996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,2026-03-04,1.0,3,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
791491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,NaT,0.0,3,NaN,NaN,NaN,NaN
791494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,NaT,0.0,3,NaN,NaN,NaN,NaN
791667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,NaT,3.0,3,NaN,NaN,NaN,NaN
791886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,NaT,0.0,3,NaN,NaN,NaN,NaN
797140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,NaT,0.0,nan,NaN,NaN,NaN,NaN

looks like join failed completely

probably the type mismatch on asset id

In [46]:
aims.dtypes

asset_id                      str
asset_name                    str
asset_sub_type                str
primary_purpose               str
alternative_purpose_1         str
alternative_purpose_2         str
asset_length              float64
toe_level                 float64
protection_type               str
asset_maintainer              str
asset_operator                str
asset_owner                   str
current_condition             str
target_condition              str
current_sop               float64
current_sop_date              str
design_sop                float64
design_sop_dqf                str
design_ucl                float64
year_last_refurbished     float64
last_inspection_date          str
next_inspection_date          str
asset_start_date              str
actual_dcl                float64
actual_dcl_dqf                str
actual_ucl                float64
actual_ucl_dqf                str
design_dcl                float64
bank                          str
effective_cl              float64
effective_cl_dqf              str
include_in_flood_map          str
water_management_area         str
local_authority               str
frms_code                     str
water_course_name             str
geometry                 geometry
dtype: object

In [47]:
eir_cs_clean.dtypes

asset_id                                 int64
eir_inspection_date             datetime64[us]
eir_condition_grade                    float64
eir_asset_target_condition                 str
eir_below_required_condition               str
eir_year_last_refurbished              float64
eir_repair_deadline                        str
eir_agreed_by_engineer                     str
dtype: object

In [48]:
aims["asset_id"] = aims["asset_id"].astype("int64")

aims.dtypes

asset_id                    int64
asset_name                    str
asset_sub_type                str
primary_purpose               str
alternative_purpose_1         str
alternative_purpose_2         str
asset_length              float64
toe_level                 float64
protection_type               str
asset_maintainer              str
asset_operator                str
asset_owner                   str
current_condition             str
target_condition              str
current_sop               float64
current_sop_date              str
design_sop                float64
design_sop_dqf                str
design_ucl                float64
year_last_refurbished     float64
last_inspection_date          str
next_inspection_date          str
asset_start_date              str
actual_dcl                float64
actual_dcl_dqf                str
actual_ucl                float64
actual_ucl_dqf                str
design_dcl                float64
bank                          str
effective_cl              float64
effective_cl_dqf              str
include_in_flood_map          str
water_management_area         str
local_authority               str
frms_code                     str
water_course_name             str
geometry                 geometry
dtype: object

In [49]:
aims.reset_index(inplace=True)
eir_clean_df.reset_index(inplace=True)

joined_aims_eir = aims.merge(eir_cs_clean, on="asset_id", how="inner", validate="1:1")

In [50]:
joined_aims_eir

,index,asset_id,asset_name,asset_sub_type,primary_purpose,alternative_purpose_1,alternative_purpose_2,asset_length,toe_level,protection_type,...,frms_code,water_course_name,geometry,eir_inspection_date,eir_condition_grade,eir_asset_target_condition,eir_below_required_condition,eir_year_last_refurbished,eir_repair_deadline,eir_agreed_by_engineer
0,6,100006,Not Available,Engineered High Ground,Flood Risk Management,NaN,NaN,80.120003,NaN,Fluvial,...,FR/06/S807,River Tame,"MULTILINESTRING ((408224.83 291081.97, 408202....",2026-01-27,3.0,3,NaN,NaN,NaN,NaN
1,8,100010,Not Available,Engineered High Ground,Flood Risk Management,NaN,NaN,108.530000,NaN,Fluvial,...,FR/06/S807,River Tame,"MULTILINESTRING ((407246.91 291958.54, 407138....",2025-12-03,3.0,3,NaN,NaN,NaN,NaN
2,12,100015,Not Available,Wall,Flood Risk Management,NaN,NaN,329.649990,NaN,Fluvial/Tidal,...,FR/10/S013,Ditton Brook,"MULTILINESTRING ((349209.28 384525.48, 349207....",2023-11-23,4.0,3,Yes,NaN,04/02/2027,No
3,14,100016,Not Available,Wall,Flood Risk Management,NaN,NaN,113.200000,NaN,Fluvial,...,FR/10/S013,Ditton Brook,"MULTILINESTRING ((349022.17 384594.96, 349016....",2023-11-23,3.0,3,NaN,NaN,NaN,NaN
4,15,100017,Not Available,Wall,Flood Risk Management,NaN,NaN,114.160000,NaN,Fluvial,...,FR/10/S013,Ditton Brook,"MULTILINESTRING ((348927.63 384655.22, 348908....",2023-11-20,3.0,3,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35265,141970,99963,Not Available,Embankment,Flood Risk Management,NaN,NaN,276.480010,NaN,Fluvial/Tidal,...,FR/05/S103,River Trent,"MULTILINESTRING ((481937.98 373874.8, 481925.3...",2026-01-05,3.0,3,NaN,NaN,NaN,NaN
35266,141973,99966,Not Available,Embankment,Flood Risk Management,NaN,NaN,228.470000,NaN,Fluvial,...,FR/09/S108,River Gilpin,"MULTILINESTRING ((347235.59 485557.56, 347238....",2024-11-21,3.0,3,NaN,NaN,NaN,NaN
35267,141974,99967,Not Available,Embankment,Flood Risk Management,NaN,NaN,591.020020,NaN,Fluvial/Tidal,...,FR/09/S108,River Gilpin,"MULTILINESTRING ((347296.63 486289.74, 347278....",2024-11-07,3.0,3,NaN,NaN,NaN,NaN
35268,141980,99973,Not Available,Natural High Ground,Flood Risk Management,NaN,NaN,405.120000,NaN,Fluvial,...,FR/14/S139,,"MULTILINESTRING ((387686.5 169770.18, 387715.4...",2023-11-10,3.0,3,NaN,NaN,NaN,NaN
35269,141995,99995,Not Available,Embankment,Flood Risk Management,NaN,NaN,95.110001,NaN,Fluvial/Tidal,...,FR/09/S108,River Gilpin,"MULTILINESTRING ((346676.87 487905.31, 346673....",2024-11-04,3.0,3,NaN,NaN,NaN,NaN

In [51]:
print(joined_aims_eir.head())
print()
print(joined_aims_eir.info())
print()
print(joined_aims_eir.describe())

   index  asset_id     asset_name          asset_sub_type  \
0      6    100006  Not Available  Engineered High Ground
1      8    100010  Not Available  Engineered High Ground
2     12    100015  Not Available                    Wall
3     14    100016  Not Available                    Wall
4     15    100017  Not Available                    Wall

         primary_purpose alternative_purpose_1 alternative_purpose_2  \
0  Flood Risk Management                   NaN                   NaN
1  Flood Risk Management                   NaN                   NaN
2  Flood Risk Management                   NaN                   NaN
3  Flood Risk Management                   NaN                   NaN
4  Flood Risk Management                   NaN                   NaN

   asset_length  toe_level protection_type  ...   frms_code water_course_name  \
0     80.120003        NaN         Fluvial  ...  FR/06/S807        River Tame
1    108.530000        NaN         Fluvial  ...  FR/06/S807        River Tame
2    329.649990        NaN   Fluvial/Tidal  ...  FR/10/S013      Ditton Brook
3    113.200000        NaN         Fluvial  ...  FR/10/S013      Ditton Brook
4    114.160000        NaN         Fluvial  ...  FR/10/S013      Ditton Brook

                                            geometry eir_inspection_date  \
0  MULTILINESTRING ((408224.83 291081.97, 408202....          2026-01-27
1  MULTILINESTRING ((407246.91 291958.54, 407138....          2025-12-03
2  MULTILINESTRING ((349209.28 384525.48, 349207....          2023-11-23
3  MULTILINESTRING ((349022.17 384594.96, 349016....          2023-11-23
4  MULTILINESTRING ((348927.63 384655.22, 348908....          2023-11-20

  eir_condition_grade  eir_asset_target_condition  \
0                 3.0                           3
1                 3.0                           3
2                 4.0                           3
3                 3.0                           3
4                 3.0                           3

  eir_below_required_condition  eir_year_last_refurbished eir_repair_deadline  \
0                          NaN                        NaN                 NaN
1                          NaN                        NaN                 NaN
2                          Yes                        NaN          04/02/2027
3                          NaN                        NaN                 NaN
4                          NaN                        NaN                 NaN

   eir_agreed_by_engineer
0                     NaN
1                     NaN
2                      No
3                     NaN
4                     NaN

[5 rows x 45 columns]

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 35270 entries, 0 to 35269
Data columns (total 45 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   index                         35270 non-null  int64
 1   asset_id                      35270 non-null  int64
 2   asset_name                    35270 non-null  str
 3   asset_sub_type                35270 non-null  str
 4   primary_purpose               35270 non-null  str
 5   alternative_purpose_1         2050 non-null   str
 6   alternative_purpose_2         737 non-null    str
 7   asset_length                  35270 non-null  float64
 8   toe_level                     1758 non-null   float64
 9   protection_type               34979 non-null  str
 10  asset_maintainer              35270 non-null  str
 11  asset_operator                35270 non-null  str
 12  asset_owner                   35270 non-null  str
 13  current_condition             35267 non-null  str
 14  target_condition              35210 non-null  str
 15  current_sop                   3351 non-null   float64
 16  current_sop_date              2426 non-null   str
 17  design_sop                    28709 non-null  float64
 18  design_sop_dqf                1592 non-null   str
 19  design_ucl                    5199 non-null   float64
 20  year_last_refurbished         814 non-null    float64
 21  last_inspection_date          34970 non-null  str
 22  next_inspection_date          31719 non-null  str
 23  asset_start_date              18032 non-null  str
 24  actual_dcl                    23833 non-null  float64
 25  actual_dcl_dqf                23228 non-null  str
 26  actual_ucl                    23789 non-null  float64
 27  actual_ucl_dqf                23170 non-null  str
 28  design_dcl                    6277 non-null   float64
 29  bank                          32375 non-null  str
 30  effective_cl                  12978 non-null  float64
 31  effective_cl_dqf              12369 non-null  str
 32  include_in_flood_map          34529 non-null  str
 33  water_management_area         35270 non-null  str
 34  local_authority               35270 non-null  str
 35  frms_code                     35270 non-null  str
 36  water_course_name             35270 non-null  str
 37  geometry                      35270 non-null  geometry
 38  eir_inspection_date           35263 non-null  datetime64[us]
 39  eir_condition_grade           35270 non-null  float64
 40  eir_asset_target_condition    35270 non-null  str
 41  eir_below_required_condition  2142 non-null   str
 42  eir_year_last_refurbished     52 non-null     float64
 43  eir_repair_deadline           1290 non-null   str
 44  eir_agreed_by_engineer        1536 non-null   str
dtypes: datetime64[us](1), float64(12), geometry(1), int64(2), str(29)
memory usage: 12.1 MB
None

               index       asset_id  asset_length   toe_level   current_sop  \
count   35270.000000   35270.000000  35270.000000  1758.00000   3351.000000
mean    76874.917465  176128.555373    408.283606     4.19083    316.182930
min         6.000000       4.000000      0.010000    -3.00000      1.000000
25%     42262.250000   50946.250000     44.032500     2.00000     70.000000
50%     81300.000000  121375.000000    159.305000     3.00000    100.000000
75%    105764.500000  176747.750000    446.790010     4.50000    200.000000
max    141995.000000  796170.000000  24196.820000   136.14999  10000.000000
std     38693.454668  181972.877907    828.018773     8.14676    625.446995

         design_sop   design_ucl  year_last_refurbished    actual_dcl  \
count  28709.000000  5199.000000             814.000000  23833.000000
mean     112.057752    24.717691            2012.700246     19.114463
min        0.000000     0.000000            1950.000000     -0.020000
25%        5.000000     4.880000            2010.000000      4.470000
50%       50.000000    10.300000            2014.000000      6.840000
75%      100.000000    29.000000            2017.000000     19.549999
max     9999.000000   235.870000            2024.000000    233.910000
std      233.377724    34.196913               7.187085     28.483783

         actual_ucl    design_dcl  effective_cl         eir_inspection_date  \
count  23789.000000   6277.000000  12978.000000                       35263
mean      19.284239     27.247951     13.878161  2025-01-26 16:58:53.947764
min       -0.020000  -9999.000000     -0.200000         1996-08-12 00:00:00
25%        4.600000      4.330000      3.960000         2025-01-17 00:00:00
50%        6.970000      9.000000      5.780000         2025-07-23 00:00:00
75%       19.840000     30.500000      8.729999         2025-11-11 00:00:00
max      235.870000  18900.000000    233.920000         2026-03-04 00:00:00
std       28.523709    272.152161     23.228235                         NaN

       eir_condition_grade  eir_year_last_refurbished
count         35270.000000                  52.000000
mean              2.846158                2011.192308
min               0.000000                1994.000000
25%               2.000000                2011.250000
50%               3.000000                2013.000000
75%               3.000000                2015.000000
max               5.000000                2020.000000
std               0.646328                   7.076718

In [52]:
condition_coverage_check = joined_aims_eir[
    (joined_aims_eir["current_condition"].isin([" ", "", "\t"]) | joined_aims_eir["current_condition"].isna()) & joined_aims_eir["eir_condition_grade"].notna()
]

condition_coverage_check

,index,asset_id,asset_name,asset_sub_type,primary_purpose,alternative_purpose_1,alternative_purpose_2,asset_length,toe_level,protection_type,...,frms_code,water_course_name,geometry,eir_inspection_date,eir_condition_grade,eir_asset_target_condition,eir_below_required_condition,eir_year_last_refurbished,eir_repair_deadline,eir_agreed_by_engineer
31455,127479,789587,Not Available,Embankment,Flood Risk Management,NaN,NaN,66.260002,NaN,Fluvial,...,FR/08/S322,,"MULTILINESTRING ((399497.688 453087.625, 39955...",2026-02-20,2.0,3,NaN,NaN,NaN,NaN
31457,127481,789594,Not Available,Engineered High Ground,Flood Risk Management,NaN,NaN,166.240010,NaN,Fluvial,...,FR/08/S322,Eller Beck,"MULTILINESTRING ((399461.969 452916.25, 399466...",2026-02-20,2.0,3,NaN,NaN,NaN,NaN
31460,127484,789599,Not Available,Engineered High Ground,Flood Risk Management,NaN,NaN,162.020000,NaN,Fluvial,...,FR/08/S322,Eller Beck,"MULTILINESTRING ((399466.875 452920.094, 39947...",2026-02-20,2.0,3,NaN,NaN,NaN,NaN

In [53]:
condition_coverage_check[["asset_id", "asset_name", "asset_sub_type", "current_condition", "eir_condition_grade"]]

,asset_id,asset_name,asset_sub_type,current_condition,eir_condition_grade
31455,789587,Not Available,Embankment,NaN,2.0
31457,789594,Not Available,Engineered High Ground,NaN,2.0
31460,789599,Not Available,Engineered High Ground,NaN,2.0

In [54]:
condition_agreement_check = joined_aims_eir[
    (joined_aims_eir["current_condition"].replace(r"^\s*$", np.nan, regex=True).astype("float32") != joined_aims_eir["eir_condition_grade"].astype("float32"))
]

condition_agreement_check[["asset_id", "asset_name", "asset_sub_type", "current_condition", "eir_condition_grade"]]

,asset_id,asset_name,asset_sub_type,current_condition,eir_condition_grade
20,102561,Not Available,Wall,,3.0
87,102980,Not Available,Natural High Ground,3,2.0
111,103157,Not Available,Embankment,3,2.0
144,103386,Not Available,Embankment,3,2.0
150,103383,Not Available,Embankment,3,2.0
...,...,...,...,...,...
35134,98692,Not Available,Embankment,3,4.0
35136,98720,Not Available,Embankment,4,3.0
35149,98824,Not Available,Embankment,4,3.0
35204,99170,Not Available,Engineered High Ground,3,4.0
35216,99293,Not Available,Engineered High Ground,3,4.0

I can immediately see that there are discrepencies in both directions - 4 (higher) in the aims download vs 3 (lower) in the EIR response, and 3 (lower) in the aims download vs 4 (higher) in the EIR response. 

My instinct at the moment is that the EIR grade should be more trustworthy because i also have the exact inspection date. I expect the discrepencies are due to recent inspections. It may be worth redownloading aims and seeing if it agrees more closely with the eir response.

---

bgs

---

In [55]:



geology_path = paths.geology_data / "625k_V5_Geology_UK_EPSG27700.gpkg"

In [56]:
import fiona 

layers = fiona.listlayers(geology_path)

layers

['625k_V5_BEDROCK_Geology',
 '625k_V5_DYKES_Geology',
 '625k_V5_FAULTS',
 '625k_V5_SUPERFICIAL_Geology',
 'layer_styles']

In [57]:
bedrock_layer = layers[0]

superficial_geo_layer = layers[3]

In [58]:
bedrock_gdf = gpd.read_file(geology_path, layer=bedrock_layer)

superficial_geo_gdf = gpd.read_file(geology_path, layer=superficial_geo_layer)

In [59]:
bedrock_gdf.describe()

,MAX_TIME_Y,MIN_TIME_Y,MAX_INDEX,MIN_INDEX,BGSREF,BGSREF_LEX,BGSREF_FM,BGSREF_GP,BGSREF_RK,MSLINK
count,1.124400e+04,1.124400e+04,1.124400e+04,1.124400e+04,11244.000000,11244.000000,11244.000000,11244.000000,11244.000000,11244.000000
mean,8.018894e+08,3.700524e+08,1.674157e+06,1.579514e+06,453.170491,502.692903,503.572750,497.154571,490.695749,18132.486037
std,1.147858e+09,2.168436e+08,7.808241e+05,5.676878e+05,298.843325,310.630659,310.328452,306.697591,307.492303,698.331536
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000,2.000000,2.000000,2.000000,2.000000,17464.000000
25%,3.135000e+08,2.482000e+08,1.321239e+06,1.319999e+06,169.000000,230.000000,234.000000,234.000000,202.000000,17512.000000
50%,4.190000e+08,3.910000e+08,1.340199e+06,1.330399e+06,426.000000,487.000000,513.000000,480.000000,620.000000,18082.000000
75%,1.000000e+09,5.450000e+08,2.199999e+06,2.199999e+06,733.250000,773.000000,773.000000,773.000000,743.000000,18165.000000
max,4.600000e+09,1.600000e+09,9.999999e+06,9.999999e+06,962.000000,966.000000,966.000000,966.000000,1000.000000,19915.000000

In [60]:
superficial_geo_gdf.describe()

,MAX_AGE_NO,MIN_AGE_NO,BGSREF,BGSREF_LEX,BGSREF_FM,BGSREF_GP,BGSREF_RK,MSLINK
count,1.065100e+04,1.065100e+04,10651.000000,10651.000000,10651.000000,10651.000000,10651.000000,10651.000000
mean,1.209338e+06,1.209310e+06,356.427378,346.862642,346.862642,346.862642,528.708666,2895.858323
std,5.264610e+05,5.264661e+05,318.914937,312.445843,312.445843,312.445843,212.432327,3.400486
min,1.110000e+06,1.110000e+06,3.000000,3.000000,3.000000,3.000000,33.000000,2892.000000
25%,1.110000e+06,1.110000e+06,20.000000,20.000000,20.000000,20.000000,343.000000,2893.000000
50%,1.110000e+06,1.110000e+06,400.000000,400.000000,400.000000,400.000000,407.000000,2896.000000
75%,1.110000e+06,1.110000e+06,624.000000,624.000000,624.000000,624.000000,624.000000,2898.000000
max,4.000000e+06,4.000000e+06,1000.000000,1000.000000,1000.000000,1000.000000,923.000000,2906.000000

In [61]:
bedrock_gdf.head()

,LEX,LEX_D,LEX_RCS,RCS,RCS_X,RCS_D,RANK,BED_EQ,BED_EQ_D,MB_EQ,...,BGSREF_GP,BGSREF_RK,SHEET,VERSION,RELEASED,NOM_SCALE,NOM_OS_YR,NOM_BGS_YR,MSLINK,geometry
0,UISD,"UNNAMED IGNEOUS INTRUSION, LATE SILURIAN TO EA...",UISD-MFIR,MFIR,MFIR,MAFIC IGNEOUS-ROCK,INTRUSION,UISD,"UNNAMED IGNEOUS INTRUSION, LATE SILURIAN TO EA...",NoPar,...,773,773,625k_V5_Bedrock,5.17,11- 2-2008,625000,2005 HC,2007,18166,"MULTIPOLYGON (((274375.248 555042.401, 274315...."
1,UISD,"UNNAMED IGNEOUS INTRUSION, LATE SILURIAN TO EA...",UISD-MFIR,MFIR,MFIR,MAFIC IGNEOUS-ROCK,INTRUSION,UISD,"UNNAMED IGNEOUS INTRUSION, LATE SILURIAN TO EA...",NoPar,...,773,773,625k_V5_Bedrock,5.17,11- 2-2008,625000,2005 HC,2007,18166,"MULTIPOLYGON (((273618.809 553462.498, 273661...."
2,UISD,"UNNAMED IGNEOUS INTRUSION, LATE SILURIAN TO EA...",UISD-MFIR,MFIR,MFIR,MAFIC IGNEOUS-ROCK,INTRUSION,UISD,"UNNAMED IGNEOUS INTRUSION, LATE SILURIAN TO EA...",NoPar,...,773,773,625k_V5_Bedrock,5.17,11- 2-2008,625000,2005 HC,2007,18166,"MULTIPOLYGON (((270985.247 554515.841, 270985...."
3,UISD,"UNNAMED IGNEOUS INTRUSION, LATE SILURIAN TO EA...",UISD-MFIR,MFIR,MFIR,MAFIC IGNEOUS-ROCK,INTRUSION,UISD,"UNNAMED IGNEOUS INTRUSION, LATE SILURIAN TO EA...",NoPar,...,773,773,625k_V5_Bedrock,5.17,11- 2-2008,625000,2005 HC,2007,18166,"MULTIPOLYGON (((273409.542 555538.671, 273361...."
4,UISD,"UNNAMED IGNEOUS INTRUSION, LATE SILURIAN TO EA...",UISD-MFIR,MFIR,MFIR,MAFIC IGNEOUS-ROCK,INTRUSION,UISD,"UNNAMED IGNEOUS INTRUSION, LATE SILURIAN TO EA...",NoPar,...,773,773,625k_V5_Bedrock,5.17,11- 2-2008,625000,2005 HC,2007,18166,"MULTIPOLYGON (((271835.801 556443.7, 271770.11..."

In [62]:
superficial_geo_gdf.head()

,LEX_ROCK,LEX,LEX_D,ROCK,ROCK_D,RCS,RCS_D,RANK,BED_EQ,BED_EQ_D,...,BGSREF_GP,BGSREF_RK,SHEET,VERSION,RELEASED,NOM_SCALE,NOM_OS_YR,NOM_BGS_YR,MSLINK,geometry
0,ALV-CLSS,ALV,ALLUVIUM,CLSS,"CLAY, SILT AND SAND",CLAY + SILT + SANDU,NaN,NaN,NaN,NaN,...,400,923,UK_Superficial_625k_v4,1.10,30- 4-2003,625000,No Date,No Date,2896,"MULTIPOLYGON (((213123.972 56621.88, 213172.77..."
1,PEAT-PEAT,PEAT,PEAT,PEAT,PEAT,PEAT,PEAT,NaN,NaN,NaN,...,624,624,UK_Superficial_625k_v4,1.10,30- 4-2003,625000,No Date,No Date,2894,"MULTIPOLYGON (((444536.549 1174121.207, 444809..."
2,ALV-CLSS,ALV,ALLUVIUM,CLSS,"CLAY, SILT AND SAND",CLAY + SILT + SANDU,NaN,NaN,NaN,NaN,...,400,923,UK_Superficial_625k_v4,1.10,30- 4-2003,625000,No Date,No Date,2896,"MULTIPOLYGON (((354575.764 192885.366, 354790...."
3,ALV-CLSS,ALV,ALLUVIUM,CLSS,"CLAY, SILT AND SAND",CLAY + SILT + SANDU,NaN,NaN,NaN,NaN,...,400,923,UK_Superficial_625k_v4,1.10,30- 4-2003,625000,No Date,No Date,2896,"MULTIPOLYGON (((212503.884 916998.194, 212615...."
4,ALV-CLSS,ALV,ALLUVIUM,CLSS,"CLAY, SILT AND SAND",CLAY + SILT + SANDU,NaN,NaN,NaN,NaN,...,400,923,UK_Superficial_625k_v4,1.10,30- 4-2003,625000,No Date,No Date,2896,"MULTIPOLYGON (((242711.784 60368.354, 243051.4..."

i need to find a data description/dictionary/info doc to interpret these fields. There was one in the download file for the geosure dataset, but not for this one it seems.

In [63]:
bedrock_gdf.columns

Index(['LEX', 'LEX_D', 'LEX_RCS', 'RCS', 'RCS_X', 'RCS_D', 'RANK', 'BED_EQ',
       'BED_EQ_D', 'MB_EQ', 'MB_EQ_D', 'FM_EQ', 'FM_EQ_D', 'SUBGP_EQ',
       'SUBGP_EQ_D', 'GP_EQ', 'GP_EQ_D', 'SUPGP_EQ', 'SUPGP_EQ_D',
       'MAX_TIME_D', 'MIN_TIME_D', 'MAX_TIME_Y', 'MIN_TIME_Y', 'MAX_INDEX',
       'MIN_INDEX', 'MAX_AGE', 'MIN_AGE', 'MAX_EPOCH', 'MIN_EPOCH',
       'MAX_SUBPER', 'MIN_SUBPER', 'MAX_PERIOD', 'MIN_PERIOD', 'MAX_ERA',
       'MIN_ERA', 'MAX_EON', 'MIN_EON', 'PREV_NAME', 'BGSTYPE', 'LEX_RCS_I',
       'LEX_RCS_D', 'MAP_CODE', 'AGE_ONEGL', 'BGSREF', 'BGSREF_LEX',
       'BGSREF_FM', 'BGSREF_GP', 'BGSREF_RK', 'SHEET', 'VERSION', 'RELEASED',
       'NOM_SCALE', 'NOM_OS_YR', 'NOM_BGS_YR', 'MSLINK', 'geometry'],
      dtype='str')

https://www.bgs.ac.uk/technologies/the-bgs-lexicon-of-named-rock-units/

In [64]:
geology_columns = [
    "LEX",
    "LEX_D",
    "LEX_RCS",
    "RCS",
    "RCS_X",
    "RCS_D",
    "MAX_PERIOD", 
    "MAX_ERA",
    "BED_EQ",
    "BED_EQ_D",
]


bedrock_gdf[geology_columns]

,LEX,LEX_D,LEX_RCS,RCS,RCS_X,RCS_D,MAX_PERIOD,MAX_ERA,BED_EQ,BED_EQ_D
0,UISD,"UNNAMED IGNEOUS INTRUSION, LATE SILURIAN TO EA...",UISD-MFIR,MFIR,MFIR,MAFIC IGNEOUS-ROCK,SILURIAN,PALAEOZOIC,UISD,"UNNAMED IGNEOUS INTRUSION, LATE SILURIAN TO EA..."
1,UISD,"UNNAMED IGNEOUS INTRUSION, LATE SILURIAN TO EA...",UISD-MFIR,MFIR,MFIR,MAFIC IGNEOUS-ROCK,SILURIAN,PALAEOZOIC,UISD,"UNNAMED IGNEOUS INTRUSION, LATE SILURIAN TO EA..."
2,UISD,"UNNAMED IGNEOUS INTRUSION, LATE SILURIAN TO EA...",UISD-MFIR,MFIR,MFIR,MAFIC IGNEOUS-ROCK,SILURIAN,PALAEOZOIC,UISD,"UNNAMED IGNEOUS INTRUSION, LATE SILURIAN TO EA..."
3,UISD,"UNNAMED IGNEOUS INTRUSION, LATE SILURIAN TO EA...",UISD-MFIR,MFIR,MFIR,MAFIC IGNEOUS-ROCK,SILURIAN,PALAEOZOIC,UISD,"UNNAMED IGNEOUS INTRUSION, LATE SILURIAN TO EA..."
4,UISD,"UNNAMED IGNEOUS INTRUSION, LATE SILURIAN TO EA...",UISD-MFIR,MFIR,MFIR,MAFIC IGNEOUS-ROCK,SILURIAN,PALAEOZOIC,UISD,"UNNAMED IGNEOUS INTRUSION, LATE SILURIAN TO EA..."
...,...,...,...,...,...,...,...,...,...,...
11239,WHCK,WHITE CHALK SUBGROUP,WHCK-CHLK,CHLK,CHLK,CHALK,CRETACEOUS,MESOZOIC,NotAp,Not Applicable
11240,WHCK,WHITE CHALK SUBGROUP,WHCK-CHLK,CHLK,CHLK,CHALK,CRETACEOUS,MESOZOIC,NotAp,Not Applicable
11241,WHCK,WHITE CHALK SUBGROUP,WHCK-CHLK,CHLK,CHLK,CHALK,CRETACEOUS,MESOZOIC,NotAp,Not Applicable
11242,WHCK,WHITE CHALK SUBGROUP,WHCK-CHLK,CHLK,CHLK,CHALK,CRETACEOUS,MESOZOIC,NotAp,Not Applicable
11243,WHCK,WHITE CHALK SUBGROUP,WHCK-CHLK,CHLK,CHLK,CHALK,CRETACEOUS,MESOZOIC,NotAp,Not Applicable

anything with a "_D" suffix is a human readable description.

ive found data descriptions for the 50k dataset, but not yet for the 625k dataset (the one im actually using). I think its safe to assume these column descriptions are transferrable for now. 

https://earthwise.bgs.ac.uk/index.php/OR/16/046_Technical_information

lex = lexicon
rcs = rock classification code
rank = "Rank of the unit in the lithostratigraphical or lithodemic hierarchy: e.g. BED or SUITE"
...


looks like theres a few different types of information, but several columns are going to contain overlapping signal. most obvious example is the _D descriptions - exactly the same info as without the suffix but displayed differently. Also, _X suffixes appear to stand for extended or expanded - all the information as the non suffixed column plus something extra, e.g. with the rcs rock code, its the same rock code plus some other codes.

So obviously this will be important for feature selection, either only selecting the column with the most signal or combining some of them into single features. But I don't think i have enough context to decide which columns this will be at the moment, so i will keep them all in the join and deal with them in another notebook

In [65]:
bedrock_gdf[["RCS", "RCS_X"]]

        RCS RCS_X
0      MFIR  MFIR
1      MFIR  MFIR
2      MFIR  MFIR
3      MFIR  MFIR
4      MFIR  MFIR
...     ...   ...
11239  CHLK  CHLK
11240  CHLK  CHLK
11241  CHLK  CHLK
11242  CHLK  CHLK
11243  CHLK  CHLK

[11244 rows x 2 columns]

In [66]:
bedrock_gdf["RCS"].unique()

<StringArray>
[  'MFIR',  'WACKE',   'CHSA',   'LATM',  'FELSR',   'SDSM',   'PSPE',
   'SDBC',   'GSSC',   'SCON',  'MLMST',  'CLSSG',  'GNSMF',  'MFTUF',
   'SSCL',   'MDSS',   'PGCP',   'SDSL',  'QZITE',   'SLAR',   'SARL',
   'MDCB',   'PYRR',   'LSSM',   'LSSA',    'PSP',   'STMD',   'LMAS',
  'SISDM',   'MDSL',   'DBAT',   'MSLS',  'PSAMM',   'DLDO',   'MSCI',
   'MDSC',   'CHLK',   'LATF',   'SDLM', 'MFLAVA',  'SEDS2',   'GNSS',
 'SEMPEL',   'CYCC',   'SMSC',   'LMCM',    'PEL',  'FTUFF',   'SCSM',
   'CSSM', 'CLSISA',   'LMCS',   'CYCS',   'UMFT',   'LTVS',   'GPSP',
  'HBSCH', 'DIAMIT',   'SDBR',   'SPPE',   'DOLO',   'LSMD',   'MIGM',
   'LMST',  'QAREN',   'PSSP',   'SCAR',  'MVIVS',   'MSDR',  'MYCFB',
    'SYR',   'SMLP',   'LATU',   'COSD',  'FLAVA',   'SCHM',    'ANO',
   'MAFI',   'BCSD',    'SCH',   'MSSP',  'PPSPC',   'CLLI', 'BRCMBR',
   'SCGS',   'SDAR']
Length: 86, dtype: str

In [67]:
bedrock_gdf["RCS_X"].unique()

<StringArray>
[                                              'MFIR',
                                              'WACKE',
                                        'CHLK + SDST',
                                     'MFLAVA + MFTUF',
                                              'FELSR',
                                 'MDST + SDST + SLST',
                                        'PEL + PSAMM',
                                 'BREC + CONG + SDST',
                         'CLAY + GRAV + SANDU + SILT',
                                        'CONG + SDST',
                                              'MLMST',
                                              'GNSMF',
                                              'MFTUF',
                                'CLAY + SANDU + SILT',
                     'CALPL + CALSIR + PELGP + PSAMM',
                                        'SDST + SLST',
                                              'QZITE',
                                 'AROC + LMST + SDST',
                             'SDST + [AROC] + [LMST]',
                               'CHRT + MDST + SMCCST',
                                               'PYRR',
                          'LMST + MDST + SDST + SLST',
                             'LMST + [AROC] + [SDST]',
                               'PEL + PSAMM + SEMPEL',
                                        'MDST + SDST',
                               'AROC + LMST + [SDST]',
                               'SDST + SLST + [MDST]',
                                 'LMST + MDST + SDST',
                                       'BATHL + DOLR',
                                              'PSAMM',
                                      'DOLMST + DOLO',
          'COAL + FECRTE + FEST + MDST + SDST + SLST',
                                 'CONG + MDST + SDST',
                                               'CHLK',
                                      'FLAVA + FTUFF',
                                      'SDST + [LMST]',
                                             'MFLAVA',
 'LMST + MDST + SDST + SLST + [CHRT] + [COAL] + [CON',
                                               'GNSS',
                                             'SEMPEL',
 'LMST + MDST + SDST + SLST + [COAL] + [SEAT] + [SIS',
                          'CONG + MDST + SDST + SLST',
                               'CAMDST + LMST + MDST',
                                                'PEL',
                                              'FTUFF',
                    'SDST + [CONG] + [MDST] + [SLST]',
                                      'CALSST + LMST',
 'MDST + SDST + SEAT + SLST + [FEST] + [LMST] + [[CO',
                                               'UMFT',
                      'LAVA + SR + TUF + VCIR + VCSR',
                                     'PSMGN + SPELGN',
                                              'HBSCH',
                                             'DIAMIT',
                                      'SDST + [BREC]',
                                       'PEL + SEMPEL',
                                               'DOLO',
                                        'LMST + MDST',
                                               'MIGM',
                                               'LMST',
                                              'QAREN',
                                   'PSAMM + [SEMPEL]',
                               'CONG + SDST + [AROC]',
                                      'MVCIR + MVCSR',
                                               'MSDR',
                                      'FBRC + MYLTIC',
                                                'SYR',
                       'MBA + MLMST + PSAMM + SEPITE',
                                         'LAVA + TUF',
                                      'CONG + [SDST]',
                                              'FLAVA',
                                               'SCHM',
                                                'ANO',
                                               'MAFI',
                                                'SCH',
                      'CALSIR + PEL + PSAMM + SEMPEL',
                                        'CLAY + LIGN',
                                       'BREC + MBREC',
                             'SDST + [CONG] + [SLST]',
                                      'SDST + [AROC]']
Length: 79, dtype: str

In [69]:
joined_aims_eir.head()

,index,asset_id,asset_name,asset_sub_type,primary_purpose,alternative_purpose_1,alternative_purpose_2,asset_length,toe_level,protection_type,...,frms_code,water_course_name,geometry,eir_inspection_date,eir_condition_grade,eir_asset_target_condition,eir_below_required_condition,eir_year_last_refurbished,eir_repair_deadline,eir_agreed_by_engineer
0,6,100006,Not Available,Engineered High Ground,Flood Risk Management,NaN,NaN,80.120003,NaN,Fluvial,...,FR/06/S807,River Tame,"MULTILINESTRING ((408224.83 291081.97, 408202....",2026-01-27,3.0,3,NaN,NaN,NaN,NaN
1,8,100010,Not Available,Engineered High Ground,Flood Risk Management,NaN,NaN,108.530000,NaN,Fluvial,...,FR/06/S807,River Tame,"MULTILINESTRING ((407246.91 291958.54, 407138....",2025-12-03,3.0,3,NaN,NaN,NaN,NaN
2,12,100015,Not Available,Wall,Flood Risk Management,NaN,NaN,329.649990,NaN,Fluvial/Tidal,...,FR/10/S013,Ditton Brook,"MULTILINESTRING ((349209.28 384525.48, 349207....",2023-11-23,4.0,3,Yes,NaN,04/02/2027,No
3,14,100016,Not Available,Wall,Flood Risk Management,NaN,NaN,113.200000,NaN,Fluvial,...,FR/10/S013,Ditton Brook,"MULTILINESTRING ((349022.17 384594.96, 349016....",2023-11-23,3.0,3,NaN,NaN,NaN,NaN
4,15,100017,Not Available,Wall,Flood Risk Management,NaN,NaN,114.160000,NaN,Fluvial,...,FR/10/S013,Ditton Brook,"MULTILINESTRING ((348927.63 384655.22, 348908....",2023-11-20,3.0,3,NaN,NaN,NaN,NaN

In [75]:
print(centroids_df.crs)

centroids_df["asset_id"] = centroids_df["asset_id"].astype("int64")

joined_geology_centroids = gpd.sjoin(
    centroids_df,
    bedrock_gdf.to_crs("EPSG:27700"),
    how="left",
    predicate="within"
)

# joined_geology_centroids

joined_aims_eir_geology = joined_aims_eir.merge(
    right=joined_geology_centroids,
    how="inner",
    on="asset_id"
)

joined_aims_eir_geology

EPSG:27700

,index,asset_id,asset_name,asset_sub_type,primary_purpose,alternative_purpose_1,alternative_purpose_2,asset_length,toe_level,protection_type,...,BGSREF_FM,BGSREF_GP,BGSREF_RK,SHEET,VERSION,RELEASED,NOM_SCALE,NOM_OS_YR,NOM_BGS_YR,MSLINK
0,6,100006,Not Available,Engineered High Ground,Flood Risk Management,NaN,NaN,80.120003,NaN,Fluvial,...,404.0,404.0,430.0,625k_V5_Bedrock,5.17,11- 2-2008,625000,2005 HC,2007,17487.0
1,8,100010,Not Available,Engineered High Ground,Flood Risk Management,NaN,NaN,108.530000,NaN,Fluvial,...,404.0,404.0,430.0,625k_V5_Bedrock,5.17,11- 2-2008,625000,2005 HC,2007,17487.0
2,12,100015,Not Available,Wall,Flood Risk Management,NaN,NaN,329.649990,NaN,Fluvial/Tidal,...,404.0,404.0,430.0,625k_V5_Bedrock,5.17,11- 2-2008,625000,2005 HC,2007,17487.0
3,14,100016,Not Available,Wall,Flood Risk Management,NaN,NaN,113.200000,NaN,Fluvial,...,404.0,404.0,430.0,625k_V5_Bedrock,5.17,11- 2-2008,625000,2005 HC,2007,17487.0
4,15,100017,Not Available,Wall,Flood Risk Management,NaN,NaN,114.160000,NaN,Fluvial,...,404.0,404.0,430.0,625k_V5_Bedrock,5.17,11- 2-2008,625000,2005 HC,2007,17487.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35265,141970,99963,Not Available,Embankment,Flood Risk Management,NaN,NaN,276.480010,NaN,Fluvial/Tidal,...,404.0,404.0,633.0,625k_V5_Bedrock,5.17,11- 2-2008,625000,2005 HC,2007,17486.0
35266,141973,99966,Not Available,Embankment,Flood Risk Management,NaN,NaN,228.470000,NaN,Fluvial,...,45.0,45.0,633.0,625k_V5_Bedrock,5.17,11- 2-2008,625000,2005 HC,2007,19739.0
35267,141974,99967,Not Available,Embankment,Flood Risk Management,NaN,NaN,591.020020,NaN,Fluvial/Tidal,...,45.0,45.0,633.0,625k_V5_Bedrock,5.17,11- 2-2008,625000,2005 HC,2007,19739.0
35268,141980,99973,Not Available,Natural High Ground,Flood Risk Management,NaN,NaN,405.120000,NaN,Fluvial,...,743.0,743.0,48.0,625k_V5_Bedrock,5.17,11- 2-2008,625000,2005 HC,2007,17482.0
35269,141995,99995,Not Available,Embankment,Flood Risk Management,NaN,NaN,95.110001,NaN,Fluvial/Tidal,...,45.0,45.0,633.0,625k_V5_Bedrock,5.17,11- 2-2008,625000,2005 HC,2007,19739.0

In [76]:
# superficial_geo_gdf

joined_super_centroids = gpd.sjoin(
    centroids_df,
    superficial_geo_gdf.to_crs("EPSG:27700"),
    how="left",
    predicate="within"
)

# joined_geology_centroids

joined_aims_eir_geology = joined_aims_eir_geology.merge(
    right=joined_super_centroids,
    how="inner",
    on="asset_id"
)

joined_aims_eir_geology

,index,asset_id,asset_name,asset_sub_type,primary_purpose,alternative_purpose_1,alternative_purpose_2,asset_length,toe_level,protection_type,...,BGSREF_FM_y,BGSREF_GP_y,BGSREF_RK_y,SHEET_y,VERSION_y,RELEASED_y,NOM_SCALE_y,NOM_OS_YR_y,NOM_BGS_YR_y,MSLINK_y
0,6,100006,Not Available,Engineered High Ground,Flood Risk Management,NaN,NaN,80.120003,NaN,Fluvial,...,3.0,3.0,407.0,UK_Superficial_625k_v4,1.10,30- 4-2003,625000,No Date,No Date,2899.0
1,8,100010,Not Available,Engineered High Ground,Flood Risk Management,NaN,NaN,108.530000,NaN,Fluvial,...,3.0,3.0,407.0,UK_Superficial_625k_v4,1.10,30- 4-2003,625000,No Date,No Date,2899.0
2,12,100015,Not Available,Wall,Flood Risk Management,NaN,NaN,329.649990,NaN,Fluvial/Tidal,...,400.0,400.0,923.0,UK_Superficial_625k_v4,1.10,30- 4-2003,625000,No Date,No Date,2896.0
3,14,100016,Not Available,Wall,Flood Risk Management,NaN,NaN,113.200000,NaN,Fluvial,...,400.0,400.0,923.0,UK_Superficial_625k_v4,1.10,30- 4-2003,625000,No Date,No Date,2896.0
4,15,100017,Not Available,Wall,Flood Risk Management,NaN,NaN,114.160000,NaN,Fluvial,...,400.0,400.0,923.0,UK_Superficial_625k_v4,1.10,30- 4-2003,625000,No Date,No Date,2896.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35265,141970,99963,Not Available,Embankment,Flood Risk Management,NaN,NaN,276.480010,NaN,Fluvial/Tidal,...,400.0,400.0,923.0,UK_Superficial_625k_v4,1.10,30- 4-2003,625000,No Date,No Date,2896.0
35266,141973,99966,Not Available,Embankment,Flood Risk Management,NaN,NaN,228.470000,NaN,Fluvial,...,400.0,400.0,923.0,UK_Superficial_625k_v4,1.10,30- 4-2003,625000,No Date,No Date,2896.0
35267,141974,99967,Not Available,Embankment,Flood Risk Management,NaN,NaN,591.020020,NaN,Fluvial/Tidal,...,400.0,400.0,923.0,UK_Superficial_625k_v4,1.10,30- 4-2003,625000,No Date,No Date,2896.0
35268,141980,99973,Not Available,Natural High Ground,Flood Risk Management,NaN,NaN,405.120000,NaN,Fluvial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35269,141995,99995,Not Available,Embankment,Flood Risk Management,NaN,NaN,95.110001,NaN,Fluvial/Tidal,...,400.0,400.0,923.0,UK_Superficial_625k_v4,1.10,30- 4-2003,625000,No Date,No Date,2896.0