In [125]:
import geopandas as gpd
import pandas as pd
from project_paths import paths

In [126]:
aims = gpd.read_file(paths.aims_data / "aims.gpkg")
aims

,asset_id,asset_name,asset_sub_type,primary_purpose,alternative_purpose_1,alternative_purpose_2,asset_length,toe_level,protection_type,asset_maintainer,...,design_dcl,bank,effective_cl,effective_cl_dqf,include_in_flood_map,water_management_area,local_authority,frms_code,water_course_name,geometry
0,10,Not Available,Natural High Ground,Flood Risk Management,NaN,NaN,77.559998,NaN,Fluvial,"Private individual, Company or Charity",...,NaN,Left,NaN,NaN,Not Yet Considered,Wessex,Dorset,FR/13/S387,River Frome,"MULTILINESTRING ((363278.14 94625.53, 363262.8..."
1,100,Not Available,Natural High Ground,Flood Risk Management,NaN,NaN,65.769997,NaN,Fluvial,"Private individual, Company or Charity",...,NaN,Left,NaN,NaN,Not Yet Considered,Wessex,Dorset,FR/13/S412,River Asker,"MULTILINESTRING ((347350.2 92927.23, 347369.8 ..."
2,1000,Not Available,Natural High Ground,Flood Risk Management,NaN,NaN,156.280000,NaN,Fluvial,"Private individual, Company or Charity",...,NaN,Right,NaN,NaN,Not Yet Considered,Wessex,"Bournemouth, Christchurch and Poole",FR/13/S282,River Avon,"MULTILINESTRING ((414064.24 98893.53, 414032.3..."
3,10000,Not Available,Natural High Ground,Flood Risk Management,NaN,NaN,11.310000,NaN,Fluvial,"Private individual, Company or Charity",...,NaN,Left,NaN,NaN,Considered and Rejected,Yorkshire,Kirklees,FR/08/S658,River Dearne,"MULTILINESTRING ((424639.79 409988.03, 424628...."
4,100002,Not Available,Natural High Ground,Flood Risk Management,NaN,NaN,467.100010,NaN,Fluvial,"Private individual, Company or Charity",...,NaN,Right,NaN,NaN,Considered and Rejected,Wessex,North Somerset,FR/14/S100,Land Yeo,"MULTILINESTRING ((340535.23 171088.47, 340512...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141991,99985,Not Available,Embankment,Flood Risk Management,NaN,NaN,231.460010,NaN,Fluvial,"Private individual, Company or Charity",...,NaN,Right,91.07,crest_level_dqf_1,Considered and Rejected,Cumbria and Lancashire,South Lakeland,FR/09/S099,Great Langdale Beck,"MULTILINESTRING ((329363.82 506093.59, 329268...."
141992,99990,Not Available,Natural High Ground,Flood Risk Management,NaN,NaN,153.050000,NaN,Fluvial,"Private individual, Company or Charity",...,NaN,Right,NaN,NaN,Considered and Rejected,Wessex,North Somerset,FR/14/S010,Cross Rhyne,"MULTILINESTRING ((332827.83 159144.77, 332847...."
141993,99991,Not Available,Natural High Ground,Flood Risk Management,NaN,NaN,154.750000,NaN,Fluvial,"Private individual, Company or Charity",...,NaN,Left,NaN,NaN,Considered and Rejected,Wessex,North Somerset,FR/14/S010,Cross Rhyne,"MULTILINESTRING ((332829.81 159139.4, 332834.6..."
141994,99992,Not Available,Natural High Ground,Flood Risk Management,NaN,NaN,342.660000,NaN,Fluvial,"Private individual, Company or Charity",...,NaN,Left,NaN,NaN,Not Yet Considered,Hertfordshire and North London,Welwyn Hatfield,FR/17/S027,River Lea or Lee,"MULTILINESTRING ((522572.99 211448.21, 522549...."
141995,99995,Not Available,Embankment,Flood Risk Management,NaN,NaN,95.110001,NaN,Fluvial/Tidal,Environment Agency,...,NaN,Right,7.19,crest_level_dqf_1,Considered and Rejected,Cumbria and Lancashire,South Lakeland,FR/09/S108,River Gilpin,"MULTILINESTRING ((346676.87 487905.31, 346673...."

In [127]:
aims.crs

<Projected CRS: EPSG:27700>
Name: OSGB36 / British National Grid
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: United Kingdom (UK) - offshore to boundary of UKCS within 49°45'N to 61°N and 9°W to 2°E; onshore Great Britain (England, Wales and Scotland). Isle of Man onshore.
- bounds: (-9.01, 49.75, 2.01, 61.01)
Coordinate Operation:
- name: British National Grid
- method: Transverse Mercator
Datum: Ordnance Survey of Great Britain 1936
- Ellipsoid: Airy 1830
- Prime Meridian: Greenwich

In [128]:
centroids_df = gpd.GeoDataFrame(aims["asset_id"], geometry=aims.geometry.centroid, crs=aims.crs)
centroids_df

       asset_id                       geometry
0            10   POINT (363244.258 94642.589)
1           100   POINT (347376.191 92947.314)
2          1000   POINT (414034.541 98965.406)
3         10000    POINT (424634.14 409988.33)
4        100002  POINT (340401.839 170970.115)
...         ...                            ...
141991    99985  POINT (329259.644 506052.335)
141992    99990  POINT (332890.139 159185.737)
141993    99991  POINT (332892.787 159179.196)
141994    99992  POINT (522517.344 211601.944)
141995    99995  POINT (346643.627 487937.728)

[141996 rows x 2 columns]

In [129]:
eir_df = pd.read_csv(paths.ea_data / "ea_eir_data.csv")
eir_df

,Asset AIMS ID,Completion Date,Calculated Condition,Asset FCRM Target Condition,BRC,Year Last Refurbished,Repair Deadline Date,Agreed by Designated Engineer,Asset Year Last Refurbished
0,10,28/09/2009,888.0,888,888,888.0,888,888,888.0
1,100,NaN,888.0,888,888,888.0,888,888,888.0
2,100,09/08/2018,888.0,888,888,888.0,888,888,888.0
3,100,02/08/2019,888.0,888,888,888.0,888,888,888.0
4,100,20/10/2020,888.0,888,888,888.0,888,888,888.0
...,...,...,...,...,...,...,...,...,...
1037159,99999,31/10/2018,888.0,888,888,888.0,888,888,888.0
1037160,99999,26/10/2020,888.0,888,888,888.0,888,888,888.0
1037161,99999,04/10/2021,888.0,888,888,888.0,888,888,888.0
1037162,99999,30/10/2022,888.0,888,888,888.0,888,888,888.0
1037163,99999,03/12/2024,888.0,888,888,888.0,888,888,888.0

In [130]:
print(len(eir_df["Asset AIMS ID"].unique()))
print(len(eir_df["Asset AIMS ID"]))

170329
1037164

In [131]:
import numpy as np

def convert(series: pd.Series) -> pd.Series:
    num = pd.to_numeric(series, errors="coerce")
    num_cleaned = num.where(~num.isin([888, 999]), other=np.nan)
    return num_cleaned

In [132]:
eir_df["Year Last Refurbished"] = convert(eir_df["Year Last Refurbished"])
eir_df["Asset Year Last Refurbished"] = convert(eir_df["Asset Year Last Refurbished"])

In [133]:
print(eir_df[["Asset AIMS ID", "Year Last Refurbished", "Asset Year Last Refurbished"]].describe())
print()
print(eir_df[["Asset AIMS ID", "Year Last Refurbished", "Asset Year Last Refurbished"]].info())

       Asset AIMS ID  Year Last Refurbished  Asset Year Last Refurbished
count   1.037164e+06             739.000000                   639.000000
mean    1.342191e+05            2011.047361                  2010.555556
std     1.355894e+05               6.900114                     7.162881
min     2.000000e+00            1994.000000                  1994.000000
25%     4.612300e+04            2012.000000                  2006.000000
50%     1.054460e+05            2013.000000                  2013.000000
75%     1.567400e+05            2015.000000                  2014.000000
max     7.979800e+05            2020.000000                  2020.000000

<class 'pandas.DataFrame'>
RangeIndex: 1037164 entries, 0 to 1037163
Data columns (total 3 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   Asset AIMS ID                1037164 non-null  int64
 1   Year Last Refurbished        739 non-null      float64
 2   Asset Year Last Refurbished  639 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 23.7 MB
None

In [134]:
both_but_different = eir_df[eir_df["Year Last Refurbished"].notna() & eir_df["Asset Year Last Refurbished"] & (eir_df["Year Last Refurbished"] != eir_df["Asset Year Last Refurbished"])]
both_but_different

Empty DataFrame
Columns: [Asset AIMS ID, Completion Date, Calculated Condition, Asset FCRM Target Condition, BRC, Year Last Refurbished, Repair Deadline Date, Agreed by Designated Engineer, Asset Year Last Refurbished]
Index: []

good

In [135]:
only_year = eir_df[eir_df["Year Last Refurbished"].notna() & eir_df["Asset Year Last Refurbished"].isna()]

only_asset_year = eir_df[eir_df["Year Last Refurbished"].isna() & eir_df["Asset Year Last Refurbished"].notna()]

print(len(only_year))
print(len(only_asset_year))

100
0

In [136]:
eir_df["raw Calculated Condition"] = eir_df["Calculated Condition"]
eir_df["Calculated Condition"] = convert(eir_df["Calculated Condition"])

print(len(eir_df[eir_df["raw Calculated Condition"].eq(888)]))
print(len(eir_df[eir_df["raw Calculated Condition"].eq(999)]))
print(len(eir_df[eir_df["raw Calculated Condition"].isin([0,1,2,3,4,5])]))
print(len(eir_df[eir_df["raw Calculated Condition"].isna()]))

print(len(eir_df[eir_df["Calculated Condition"].isna()]))      
print(len(eir_df[eir_df["Calculated Condition"].notna()]))

706946
22487
275571
32160
761593
275571

todo - EA say in response that the redaction is by asset, so there should be no asset ids where there is both an na and notna condition grade.

In [137]:
eir_clean_df = eir_df[eir_df["Calculated Condition"].notna()].copy()
eir_clean_df.shape

(275571, 10)

In [138]:
# currently the eir data has multiple entries per asset for multiple inspections
# so currently longitudinal.
# this will be useful for later, but for now i want a cross sectional dataset for the first steps

eir_clean_df["inspection_date"] = pd.to_datetime(eir_clean_df["Completion Date"], errors="coerce", format="%d/%m/%Y")
print(eir_clean_df.head())
print()
print(eir_clean_df["inspection_date"].isna().sum())

    Asset AIMS ID Completion Date  Calculated Condition  \
37         100006      08/06/2018                   3.0
38         100006      23/08/2018                   3.0
39         100006      26/02/2019                   3.0
40         100006      06/09/2019                   3.0
41         100006      25/06/2020                   3.0

   Asset FCRM Target Condition  BRC  Year Last Refurbished  \
37                    3 - Fair  NaN                    NaN
38                    3 - Fair  NaN                    NaN
39                    3 - Fair  NaN                    NaN
40                    3 - Fair  NaN                    NaN
41                    3 - Fair  NaN                    NaN

   Repair Deadline Date Agreed by Designated Engineer  \
37                  NaN                           NaN
38                  NaN                           NaN
39                  NaN                           NaN
40                  NaN                           NaN
41                  NaN                           NaN

    Asset Year Last Refurbished  raw Calculated Condition inspection_date
37                          NaN                       3.0      2018-06-08
38                          NaN                       3.0      2018-08-23
39                          NaN                       3.0      2019-02-26
40                          NaN                       3.0      2019-09-06
41                          NaN                       3.0      2020-06-25

2337

In [139]:
print(eir_clean_df[eir_clean_df["inspection_date"].isna()])

         Asset AIMS ID Completion Date  Calculated Condition  \
15198           103168             NaN                   0.0
15657           103248             NaN                   0.0
16065           103332             NaN                   0.0
17815           103675             NaN                   0.0
17824           103676             NaN                   0.0
...                ...             ...                   ...
1033410          99235             NaN                   0.0
1034196          99384             NaN                   0.0
1034486          99459             NaN                   0.0
1035186          99605             NaN                   0.0
1036172          99770             NaN                   0.0

        Asset FCRM Target Condition  BRC  Year Last Refurbished  \
15198                      3 - Fair  NaN                    NaN
15657                      3 - Fair  NaN                    NaN
16065                      3 - Fair  NaN                    NaN
17815                      3 - Fair  NaN                    NaN
17824                      3 - Fair  NaN                    NaN
...                             ...  ...                    ...
1033410                    3 - Fair  NaN                    NaN
1034196                    3 - Fair  NaN                    NaN
1034486                    3 - Fair  NaN                    NaN
1035186                    3 - Fair  NaN                    NaN
1036172                    3 - Fair  NaN                    NaN

        Repair Deadline Date Agreed by Designated Engineer  \
15198                    NaN                           NaN
15657                    NaN                           NaN
16065                    NaN                           NaN
17815                    NaN                           NaN
17824                    NaN                           NaN
...                      ...                           ...
1033410                  NaN                           NaN
1034196                  NaN                           NaN
1034486                  NaN                           NaN
1035186                  NaN                           NaN
1036172                  NaN                           NaN

         Asset Year Last Refurbished  raw Calculated Condition inspection_date
15198                            NaN                       0.0             NaT
15657                            NaN                       0.0             NaT
16065                            NaN                       0.0             NaT
17815                            NaN                       0.0             NaT
17824                            NaN                       0.0             NaT
...                              ...                       ...             ...
1033410                          NaN                       0.0             NaT
1034196                          NaN                       0.0             NaT
1034486                          NaN                       0.0             NaT
1035186                          NaN                       0.0             NaT
1036172                          NaN                       0.0             NaT

[2337 rows x 11 columns]

it ought to be impossible to have a grade without an inspection date?

In [140]:
print(eir_clean_df[eir_clean_df["inspection_date"].isna()][["Asset AIMS ID", "Calculated Condition"]].groupby("Calculated Condition").count())

                      Asset AIMS ID
Calculated Condition
0.0                            2248
1.0                               2
2.0                              28
3.0                              46
4.0                              12
5.0                               1

decision point - should drop these rows?

In [141]:
eir_cs = (
    eir_clean_df
    .sort_values(by = "inspection_date", ascending=False, na_position="last")
    .drop_duplicates(subset="Asset AIMS ID", keep="first")
)

print(eir_cs.info())
print()
print(eir_cs.describe())
print()
print(eir_cs.head())

<class 'pandas.DataFrame'>
Index: 36562 entries, 907310 to 930297
Data columns (total 11 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Asset AIMS ID                  36562 non-null  int64
 1   Completion Date                36554 non-null  str
 2   Calculated Condition           36562 non-null  float64
 3   Asset FCRM Target Condition    36502 non-null  str
 4   BRC                            2151 non-null   str
 5   Year Last Refurbished          52 non-null     float64
 6   Repair Deadline Date           1293 non-null   str
 7   Agreed by Designated Engineer  1539 non-null   str
 8   Asset Year Last Refurbished    43 non-null     float64
 9   raw Calculated Condition       36562 non-null  float64
 10  inspection_date                36554 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(4), int64(1), str(5)
memory usage: 3.3 MB
None

       Asset AIMS ID  Calculated Condition  Year Last Refurbished  \
count   36562.000000          36562.000000              52.000000
mean   176417.592117              2.853427            2011.192308
min         4.000000              0.000000            1994.000000
25%     51726.750000              3.000000            2011.250000
50%    122209.500000              3.000000            2013.000000
75%    176692.500000              3.000000            2015.000000
max    797527.000000              5.000000            2020.000000
std    181332.564084              0.660115               7.076718

       Asset Year Last Refurbished  raw Calculated Condition  \
count                    43.000000              36562.000000
mean                   2010.511628                  2.853427
min                    1994.000000                  0.000000
25%                    2009.000000                  3.000000
50%                    2013.000000                  3.000000
75%                    2014.000000                  3.000000
max                    2020.000000                  5.000000
std                       7.414182                  0.660115

                  inspection_date
count                       36554
mean   2024-12-07 16:02:32.847841
min           1996-08-12 00:00:00
25%           2024-11-29 00:00:00
50%           2025-07-17 00:00:00
75%           2025-11-06 00:00:00
max           2026-03-04 00:00:00
std                           NaN

        Asset AIMS ID Completion Date  Calculated Condition  \
907310         758782      04/03/2026                   3.0
907369         758843      04/03/2026                   1.0
907318         758784      04/03/2026                   2.0
906857         757948      04/03/2026                   1.0
907540         758996      04/03/2026                   1.0

       Asset FCRM Target Condition  BRC  Year Last Refurbished  \
907310                    3 - Fair  NaN                    NaN
907369                    3 - Fair  NaN                    NaN
907318                    3 - Fair  NaN                    NaN
906857                    3 - Fair  NaN                    NaN
907540                    3 - Fair  NaN                    NaN

       Repair Deadline Date Agreed by Designated Engineer  \
907310                  NaN                           NaN
907369                  NaN                           NaN
907318                  NaN                           NaN
906857                  NaN                           NaN
907540                  NaN                           NaN

        Asset Year Last Refurbished  raw Calculated Condition inspection_date
907310                          NaN                       3.0      2026-03-04
907369                          NaN                       1.0      2026-03-04
907318                          NaN                       2.0      2026-03-04
906857                          NaN                       1.0      2026-03-04
907540                          NaN                       1.0      2026-03-04

distribution of grades looks extremely unbalanced

In [142]:
eir_cs = eir_cs.rename({
    "Asset AIMS ID": "asset_id",
    "Completion Date": "eir_completion_date",
    "Calculated Condition": "eir_condition_grade",
    "Asset FCRM Target Condition": "eir_asset_target_condition",
    "BRC": "eir_below_required_condition",
    "Year Last Refurbished": "eir_year_last_refurbished",
    "Repair Deadline Date": "eir_repair_deadline",
    "Agreed by Designated Engineer": "eir_agreed_by_engineer",
    "Asset Year Last Refurbished": "eir_asset_year_last_refurbished",
    "raw Calculated Condition": "eir_raw_calculated_condition",
    "inspection_date": "eir_inspection_date",
}, axis="columns")

print(eir_cs.columns)

eir_cs = eir_cs[
    [
        "asset_id",
        "eir_inspection_date",
        "eir_condition_grade",
        "eir_asset_target_condition",
        "eir_below_required_condition",
        "eir_year_last_refurbished",
        "eir_repair_deadline",
        "eir_agreed_by_engineer",
    ]
]


eir_cs

Index(['asset_id', 'eir_completion_date', 'eir_condition_grade',
       'eir_asset_target_condition', 'eir_below_required_condition',
       'eir_year_last_refurbished', 'eir_repair_deadline',
       'eir_agreed_by_engineer', 'eir_asset_year_last_refurbished',
       'eir_raw_calculated_condition', 'eir_inspection_date'],
      dtype='str')

,asset_id,eir_inspection_date,eir_condition_grade,eir_asset_target_condition,eir_below_required_condition,eir_year_last_refurbished,eir_repair_deadline,eir_agreed_by_engineer
907310,758782,2026-03-04,3.0,3 - Fair,NaN,NaN,NaN,NaN
907369,758843,2026-03-04,1.0,3 - Fair,NaN,NaN,NaN,NaN
907318,758784,2026-03-04,2.0,3 - Fair,NaN,NaN,NaN,NaN
906857,757948,2026-03-04,1.0,3 - Fair,NaN,NaN,NaN,NaN
907540,758996,2026-03-04,1.0,3 - Fair,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
927130,791491,NaT,0.0,3 - Fair,NaN,NaN,NaN,NaN
927133,791494,NaT,0.0,3 - Fair,NaN,NaN,NaN,NaN
927250,791667,NaT,3.0,3 - Fair,NaN,NaN,NaN,NaN
927410,791886,NaT,0.0,3 - Fair,NaN,NaN,NaN,NaN
930297,797140,NaT,0.0,NaN,NaN,NaN,NaN,NaN

In [143]:
eir_cs_clean = eir_cs.copy()

target_condition_map = {
    str(grade).split(" - ")[0]: str(grade).split(" - ")[1]
    for grade in eir_cs_clean["eir_asset_target_condition"].unique().tolist()
    if grade is not np.nan and len(str(grade).split(" - ")) == 2
}

print(target_condition_map)

{'3': 'Fair', '2': 'Good', '4': 'Poor', '1': 'Very Good', '0': 'Unchecked', '5': 'Very Poor'}

In [144]:

eir_cs_clean["eir_asset_target_condition"] =  list(map(lambda x: str(x).split(" - ")[0], eir_cs_clean["eir_asset_target_condition"]))

eir_cs_clean

,asset_id,eir_inspection_date,eir_condition_grade,eir_asset_target_condition,eir_below_required_condition,eir_year_last_refurbished,eir_repair_deadline,eir_agreed_by_engineer
907310,758782,2026-03-04,3.0,3,NaN,NaN,NaN,NaN
907369,758843,2026-03-04,1.0,3,NaN,NaN,NaN,NaN
907318,758784,2026-03-04,2.0,3,NaN,NaN,NaN,NaN
906857,757948,2026-03-04,1.0,3,NaN,NaN,NaN,NaN
907540,758996,2026-03-04,1.0,3,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
927130,791491,NaT,0.0,3,NaN,NaN,NaN,NaN
927133,791494,NaT,0.0,3,NaN,NaN,NaN,NaN
927250,791667,NaT,3.0,3,NaN,NaN,NaN,NaN
927410,791886,NaT,0.0,3,NaN,NaN,NaN,NaN
930297,797140,NaT,0.0,nan,NaN,NaN,NaN,NaN

In [145]:
# joined_aims_eir = pd.DataFrame.join(aims, eir_cs_clean, on="asset_id", how="inner", validate="1:1")
# above - mismatched types - asset id is numeric in one df and string in another.
# should have a cell that specifies the schema of each df explicitly, like the naming one for eir

joined_aims_eir = pd.concat([aims.set_index("asset_id"), eir_cs_clean.set_index("asset_id")], axis=1, join="outer", verify_integrity=True)

print(joined_aims_eir.head())
print()
print(joined_aims_eir.info())
print()
print(joined_aims_eir.describe())

             asset_name       asset_sub_type        primary_purpose  \
asset_id
10        Not Available  Natural High Ground  Flood Risk Management
100       Not Available  Natural High Ground  Flood Risk Management
1000      Not Available  Natural High Ground  Flood Risk Management
10000     Not Available  Natural High Ground  Flood Risk Management
100002    Not Available  Natural High Ground  Flood Risk Management

         alternative_purpose_1 alternative_purpose_2  asset_length  toe_level  \
asset_id
10                         NaN                   NaN     77.559998        NaN
100                        NaN                   NaN     65.769997        NaN
1000                       NaN                   NaN    156.280000        NaN
10000                      NaN                   NaN     11.310000        NaN
100002                     NaN                   NaN    467.100010        NaN

         protection_type                        asset_maintainer  \
asset_id
10               Fluvial  Private individual, Company or Charity
100              Fluvial  Private individual, Company or Charity
1000             Fluvial  Private individual, Company or Charity
10000            Fluvial  Private individual, Company or Charity
100002           Fluvial  Private individual, Company or Charity

         asset_operator  ...   frms_code water_course_name  \
asset_id                 ...
10              Unknown  ...  FR/13/S387       River Frome
100             Unknown  ...  FR/13/S412       River Asker
1000            Unknown  ...  FR/13/S282        River Avon
10000           Unknown  ...  FR/08/S658      River Dearne
100002          Unknown  ...  FR/14/S100          Land Yeo

                                                   geometry  \
asset_id
10        MULTILINESTRING ((363278.14 94625.53, 363262.8...
100       MULTILINESTRING ((347350.2 92927.23, 347369.8 ...
1000      MULTILINESTRING ((414064.24 98893.53, 414032.3...
10000     MULTILINESTRING ((424639.79 409988.03, 424628....
100002    MULTILINESTRING ((340535.23 171088.47, 340512....

          eir_inspection_date eir_condition_grade  eir_asset_target_condition  \
asset_id
10                        NaT                 NaN                         NaN
100                       NaT                 NaN                         NaN
1000                      NaT                 NaN                         NaN
10000                     NaT                 NaN                         NaN
100002                    NaT                 NaN                         NaN

         eir_below_required_condition  eir_year_last_refurbished  \
asset_id
10                                NaN                        NaN
100                               NaN                        NaN
1000                              NaN                        NaN
10000                             NaN                        NaN
100002                            NaN                        NaN

          eir_repair_deadline eir_agreed_by_engineer
asset_id
10                        NaN                    NaN
100                       NaN                    NaN
1000                      NaN                    NaN
10000                     NaN                    NaN
100002                    NaN                    NaN

[5 rows x 43 columns]

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 178558 entries, 10 to 797140
Data columns (total 43 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   asset_name                    141996 non-null  str
 1   asset_sub_type                141996 non-null  str
 2   primary_purpose               141996 non-null  str
 3   alternative_purpose_1         8107 non-null    str
 4   alternative_purpose_2         2817 non-null    str
 5   asset_length                  141993 non-null  float64
 6   toe_level                     2660 non-null    float64
 7   protection_type               141359 non-null  str
 8   asset_maintainer              141996 non-null  str
 9   asset_operator                141996 non-null  str
 10  asset_owner                   141996 non-null  str
 11  current_condition             141958 non-null  str
 12  target_condition              141872 non-null  str
 13  current_sop                   4696 non-null    float64
 14  current_sop_date              3352 non-null    str
 15  design_sop                    116479 non-null  float64
 16  design_sop_dqf                2201 non-null    str
 17  design_ucl                    11055 non-null   float64
 18  year_last_refurbished         1038 non-null    float64
 19  last_inspection_date          129052 non-null  str
 20  next_inspection_date          102301 non-null  str
 21  asset_start_date              32889 non-null   str
 22  actual_dcl                    74670 non-null   float64
 23  actual_dcl_dqf                73357 non-null   str
 24  actual_ucl                    74492 non-null   float64
 25  actual_ucl_dqf                73062 non-null   str
 26  design_dcl                    12572 non-null   float64
 27  bank                          135226 non-null  str
 28  effective_cl                  20092 non-null   float64
 29  effective_cl_dqf              19071 non-null   str
 30  include_in_flood_map          140151 non-null  str
 31  water_management_area         141996 non-null  str
 32  local_authority               141996 non-null  str
 33  frms_code                     141996 non-null  str
 34  water_course_name             141996 non-null  str
 35  geometry                      141996 non-null  geometry
 36  eir_inspection_date           36554 non-null   datetime64[us]
 37  eir_condition_grade           36562 non-null   float64
 38  eir_asset_target_condition    36562 non-null   str
 39  eir_below_required_condition  2151 non-null    str
 40  eir_year_last_refurbished     52 non-null      float64
 41  eir_repair_deadline           1293 non-null    str
 42  eir_agreed_by_engineer        1539 non-null    str
dtypes: datetime64[us](1), float64(12), geometry(1), str(29)
memory usage: 59.9+ MB
None

        asset_length    toe_level   current_sop     design_sop    design_ucl  \
count  141993.000000  2660.000000   4696.000000  116479.000000  11055.000000
mean      414.089448     4.099453    286.174830      76.547549     22.917466
min         0.010000    -3.000000      0.000000       0.000000      0.000000
25%        41.869999     1.842250     50.000000       5.000000      5.280000
50%       144.230000     2.851000    100.000000       5.000000      6.900000
75%       441.500000     4.300000    200.000000      50.000000     26.000000
max     24196.820000   223.000000  10000.000000    9999.000000    276.399990
std       793.500401     9.080826    623.906862     228.633890     35.482221

       year_last_refurbished    actual_dcl    actual_ucl    design_dcl  \
count            1038.000000  74670.000000  74492.000000  12572.000000
mean             2012.736994     39.876478     40.033323     24.667833
min              1948.000000     -1.000000     -1.000000  -9999.000000
25%              2011.000000      6.080000      6.160000      5.230000
50%              2014.000000     19.837499     20.100000      6.800000
75%              2017.000000     57.150002     57.641749     26.680000
max              2024.000000    297.609990    292.260010  18900.000000
std                 7.330285     47.797064     47.560088    194.061702

       effective_cl         eir_inspection_date  eir_condition_grade  \
count  20092.000000                       36554         36562.000000
mean      19.286604  2024-12-07 16:02:32.847841             2.853427
min       -0.200000         1996-08-12 00:00:00             0.000000
25%        4.260000         2024-11-29 00:00:00             3.000000
50%        6.380000         2025-07-17 00:00:00             3.000000
75%       20.020250         2025-11-06 00:00:00             3.000000
max      284.954990         2026-03-04 00:00:00             5.000000
std       28.793228                         NaN             0.660115

       eir_year_last_refurbished
count                  52.000000
mean                 2011.192308
min                  1994.000000
25%                  2011.250000
50%                  2013.000000
75%                  2015.000000
max                  2020.000000
std                     7.076718

In [146]:
condition_coverage_check = joined_aims_eir[
    (joined_aims_eir["current_condition"].isin([" ", "", "\t"]) | joined_aims_eir["current_condition"].isna()) & joined_aims_eir["eir_condition_grade"].notna()
]

condition_coverage_check

,asset_name,asset_sub_type,primary_purpose,alternative_purpose_1,alternative_purpose_2,asset_length,toe_level,protection_type,asset_maintainer,asset_operator,...,frms_code,water_course_name,geometry,eir_inspection_date,eir_condition_grade,eir_asset_target_condition,eir_below_required_condition,eir_year_last_refurbished,eir_repair_deadline,eir_agreed_by_engineer
asset_id,,,,,,,,,,,,,,,,,,,,,
758782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,2026-03-04,3.0,3,NaN,NaN,NaN,NaN
758843,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,2026-03-04,1.0,3,NaN,NaN,NaN,NaN
758784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,2026-03-04,2.0,3,NaN,NaN,NaN,NaN
757948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,2026-03-04,1.0,3,NaN,NaN,NaN,NaN
758996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,2026-03-04,1.0,3,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
791491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,NaT,0.0,3,NaN,NaN,NaN,NaN
791494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,NaT,0.0,3,NaN,NaN,NaN,NaN
791667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,NaT,3.0,3,NaN,NaN,NaN,NaN
791886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,NaT,0.0,3,NaN,NaN,NaN,NaN
797140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,None,NaT,0.0,nan,NaN,NaN,NaN,NaN

looks like join failed completely

probably the type mismatch on asset id