In [1]:
import polars as pl

df = pl.read_csv('../data/camels_gb_v2_humaninfluence_attributes.csv')

In [2]:
df.schema

Schema([('gauge_id', Int64),
        ('benchmark_catch', String),
        ('surfacewater_abs', Float64),
        ('groundwater_abs', Float64),
        ('discharges', Float64),
        ('abs_agriculture_perc', Float64),
        ('abs_amenities_perc', Float64),
        ('abs_energy_perc', Float64),
        ('abs_environmental_perc', Float64),
        ('abs_industry_perc', Float64),
        ('abs_watersupply_perc', Float64),
        ('abs_highloss_perc', Float64),
        ('abs_mediumloss_perc', Float64),
        ('abs_lowloss_perc', Float64),
        ('abs_verylowloss_perc', Float64),
        ('num_reservoir', Int64),
        ('reservoir_cap', Float64),
        ('reservoir_contributing_area', Float64),
        ('reservoir_normalised_upstream_capacity', Float64),
        ('reservoir_he', Float64),
        ('reservoir_nav', Float64),
        ('reservoir_drain', Float64),
        ('reservoir_wr', Float64),
        ('reservoir_fs', Float64),
        ('reservoir_env', Float64),
        ('reservoir_nousedata', Float64),
        ('reservoir_year_first', Float64),
        ('reservoir_year_last', Float64)])

In [3]:
df.head()

shape: (5, 28)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ gauge_id ┆ benchmark ┆ surfacewa ┆ groundwat ┆ … ┆ reservoir ┆ reservoir ┆ reservoir ┆ reservoir │
│ ---      ┆ _catch    ┆ ter_abs   ┆ er_abs    ┆   ┆ _env      ┆ _nousedat ┆ _year_fir ┆ _year_las │
│ i64      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ a         ┆ st        ┆ t         │
│          ┆ str       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ ---       ┆ ---       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆ f64       ┆ f64       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10002    ┆ N         ┆ NaN       ┆ NaN       ┆ … ┆ NaN       ┆ NaN       ┆ NaN       ┆ NaN       │
│ 10003    ┆ N         ┆ NaN       ┆ NaN       ┆ … ┆ NaN       ┆ NaN       ┆ NaN       ┆ NaN       │
│ 1001     ┆ N         ┆ NaN       ┆ NaN       ┆ … ┆ 0.0       ┆ 100.0     ┆ NaN       ┆ NaN       │
│ 101002   ┆ N         ┆ 0.008     ┆ 0.041     ┆ … ┆ NaN       ┆ NaN       ┆ NaN       ┆ NaN       │
│ 101005   ┆ N         ┆ 0.001     ┆ 0.015     ┆ … ┆ NaN       ┆ NaN       ┆ NaN       ┆ NaN       │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
df.describe()

shape: (9, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ gauge_id  ┆ benchmark ┆ surfacewa ┆ … ┆ reservoir ┆ reservoir ┆ reservoir ┆ reservoi │
│ ---       ┆ ---       ┆ _catch    ┆ ter_abs   ┆   ┆ _env      ┆ _nousedat ┆ _year_fir ┆ r_year_l │
│ str       ┆ f64       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ a         ┆ st        ┆ ast      │
│           ┆           ┆ str       ┆ f64       ┆   ┆ f64       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 671.0     ┆ 671       ┆ 671.0     ┆ … ┆ 671.0     ┆ 671.0     ┆ 671.0     ┆ 671.0    │
│ null_coun ┆ 0.0       ┆ 0         ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 43768.396 ┆ null      ┆ NaN       ┆ … ┆ NaN       ┆ NaN       ┆ NaN       ┆ NaN      │
│           ┆ 423       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 21894.720 ┆ null      ┆ NaN       ┆ … ┆ NaN       ┆ NaN       ┆ NaN       ┆ NaN      │
│           ┆ 374       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 1001.0    ┆ N         ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 1794.0    ┆ 1873.0   │
│ 25%       ┆ 28015.0   ┆ null      ┆ 0.0       ┆ … ┆ NaN       ┆ NaN       ┆ NaN       ┆ NaN      │
│ 50%       ┆ 39127.0   ┆ null      ┆ 0.003     ┆ … ┆ NaN       ┆ NaN       ┆ NaN       ┆ NaN      │
│ 75%       ┆ 56002.0   ┆ null      ┆ 0.167     ┆ … ┆ NaN       ┆ NaN       ┆ NaN       ┆ NaN      │
│ max       ┆ 107001.0  ┆ Y         ┆ 1.628     ┆ … ┆ 1.31      ┆ 100.0     ┆ 1992.0    ┆ 1992.0   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
df.null_count()

shape: (1, 28)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ gauge_id ┆ benchmark ┆ surfacewa ┆ groundwat ┆ … ┆ reservoir ┆ reservoir ┆ reservoir ┆ reservoir │
│ ---      ┆ _catch    ┆ ter_abs   ┆ er_abs    ┆   ┆ _env      ┆ _nousedat ┆ _year_fir ┆ _year_las │
│ u32      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ a         ┆ st        ┆ t         │
│          ┆ u32       ┆ u32       ┆ u32       ┆   ┆ u32       ┆ ---       ┆ ---       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆           ┆ u32       ┆ u32       ┆ u32       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [6]:
(df.null_count() / len(df) * 100).transpose()

shape: (28, 1)
┌──────────┐
│ column_0 │
│ ---      │
│ f64      │
╞══════════╡
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ …        │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
└──────────┘