In [1]:
import polars as pl

df = pl.read_csv('../data/camels_gb_v2_hydrogeology_attributes.csv')

In [2]:
df.schema

Schema([('gauge_id', Int64),
        ('inter_high_perc', Float64),
        ('inter_mod_perc', Float64),
        ('inter_low_perc', Float64),
        ('frac_high_perc', Float64),
        ('frac_mod_perc', Float64),
        ('frac_low_perc', Float64),
        ('no_gw_perc', Float64),
        ('low_nsig_perc', Float64),
        ('nsig_low_perc', Float64)])

In [3]:
df.head()

shape: (5, 10)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ gauge_id ┆ inter_hig ┆ inter_mod ┆ inter_low ┆ … ┆ frac_low_ ┆ no_gw_per ┆ low_nsig_ ┆ nsig_low_ │
│ ---      ┆ h_perc    ┆ _perc     ┆ _perc     ┆   ┆ perc      ┆ c         ┆ perc      ┆ perc      │
│ i64      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10002    ┆ 0.0       ┆ 18.51     ┆ 0.0       ┆ … ┆ 23.59     ┆ 57.81     ┆ 0.0       ┆ 0.08      │
│ 10003    ┆ 0.0       ┆ 13.13     ┆ 0.0       ┆ … ┆ 23.09     ┆ 63.66     ┆ 0.0       ┆ 0.12      │
│ 1001     ┆ 0.0       ┆ 10.19     ┆ 0.0       ┆ … ┆ 0.0       ┆ 87.56     ┆ 0.0       ┆ 0.0       │
│ 101002   ┆ 45.27     ┆ 31.08     ┆ 0.08      ┆ … ┆ 0.0       ┆ 19.29     ┆ 0.0       ┆ 0.0       │
│ 101005   ┆ 28.84     ┆ 43.99     ┆ 0.0       ┆ … ┆ 0.0       ┆ 18.25     ┆ 0.0       ┆ 0.0       │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
df.describe()

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ gauge_id  ┆ inter_hig ┆ inter_mod ┆ … ┆ frac_low_ ┆ no_gw_per ┆ low_nsig_ ┆ nsig_low │
│ ---       ┆ ---       ┆ h_perc    ┆ _perc     ┆   ┆ perc      ┆ c         ┆ perc      ┆ _perc    │
│ str       ┆ f64       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 671.0     ┆ 671.0     ┆ 671.0     ┆ … ┆ 671.0     ┆ 671.0     ┆ 671.0     ┆ 671.0    │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 43768.396 ┆ 2.229329  ┆ 19.724545 ┆ … ┆ 14.953949 ┆ 46.349538 ┆ 0.090462  ┆ 0.218987 │
│           ┆ 423       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 21894.720 ┆ 8.706633  ┆ 14.756241 ┆ … ┆ 22.553676 ┆ 24.795644 ┆ 0.99083   ┆ 1.010701 │
│           ┆ 374       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 1001.0    ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 25%       ┆ 28015.0   ┆ 0.0       ┆ 10.06     ┆ … ┆ 0.0       ┆ 27.58     ┆ 0.0       ┆ 0.0      │
│ 50%       ┆ 39127.0   ┆ 0.0       ┆ 16.16     ┆ … ┆ 0.48      ┆ 49.68     ┆ 0.0       ┆ 0.0      │
│ 75%       ┆ 56002.0   ┆ 0.0       ┆ 25.17     ┆ … ┆ 24.65     ┆ 64.78     ┆ 0.0       ┆ 0.0      │
│ max       ┆ 107001.0  ┆ 94.3      ┆ 92.64     ┆ … ┆ 97.73     ┆ 100.0     ┆ 18.81     ┆ 11.65    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
df.null_count()

shape: (1, 10)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ gauge_id ┆ inter_hig ┆ inter_mod ┆ inter_low ┆ … ┆ frac_low_ ┆ no_gw_per ┆ low_nsig_ ┆ nsig_low_ │
│ ---      ┆ h_perc    ┆ _perc     ┆ _perc     ┆   ┆ perc      ┆ c         ┆ perc      ┆ perc      │
│ u32      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆ u32       ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [6]:
(df.null_count() / len(df) * 100).transpose()

shape: (10, 1)
┌──────────┐
│ column_0 │
│ ---      │
│ f64      │
╞══════════╡
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
└──────────┘