In [1]:
import polars as pl

df = pl.read_csv('../data/camels_gb_v2_soil_attributes.csv')

In [2]:
df.schema

Schema([('gauge_id', Int64),
        ('sand_perc', Float64),
        ('sand_perc_missing', Float64),
        ('silt_perc', Float64),
        ('silt_perc_missing', Float64),
        ('clay_perc', Float64),
        ('clay_perc_missing', Float64),
        ('organic_perc', Float64),
        ('organic_perc_missing', Float64),
        ('bulkdens', Float64),
        ('bulkdens_missing', Float64),
        ('bulkdens_5', Float64),
        ('bulkdens_50', Float64),
        ('bulkdens_95', Float64),
        ('tawc', Float64),
        ('tawc_missing', Float64),
        ('tawc_5', Float64),
        ('tawc_50', Float64),
        ('tawc_95', Float64),
        ('porosity_cosby', Float64),
        ('porosity_cosby_missing', Float64),
        ('porosity_cosby_5', Float64),
        ('porosity_cosby_50', Float64),
        ('porosity_cosby_95', Float64),
        ('porosity_hypres', Float64),
        ('porosity_hypres_missing', Float64),
        ('porosity_hypres_5', Float64),
        ('porosity_hypres_50', Float64),
        ('porosity_hypres_95', Float64),
        ('conductivity_cosby', Float64),
        ('conductivity_cosby_missing', Float64),
        ('conductivity_cosby_5', Float64),
        ('conductivity_cosby_50', Float64),
        ('conductivity_cosby_95', Float64),
        ('conductivity_hypres', Float64),
        ('conductivity_hypres_missing', Float64),
        ('conductivity_hypres_5', Float64),
        ('conductivity_hypres_50', Float64),
        ('conductivity_hypres_95', Float64),
        ('root_depth', Float64),
        ('root_depth_missing', Float64),
        ('root_depth_5', Float64),
        ('root_depth_50', Float64),
        ('root_depth_95', Float64),
        ('soil_depth_pelletier', Float64),
        ('soil_depth_pelletier_missing', Float64),
        ('soil_depth_pelletier_5', Float64),
        ('soil_depth_pelletier_50', Float64),
        ('soil_depth_pelletier_95', Float64)])

In [3]:
df.head()

shape: (5, 49)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ gauge_id ┆ sand_perc ┆ sand_perc ┆ silt_perc ┆ … ┆ soil_dept ┆ soil_dept ┆ soil_dept ┆ soil_dept │
│ ---      ┆ ---       ┆ _missing  ┆ ---       ┆   ┆ h_pelleti ┆ h_pelleti ┆ h_pelleti ┆ h_pelleti │
│ i64      ┆ f64       ┆ ---       ┆ f64       ┆   ┆ er_missin ┆ er_5      ┆ er_50     ┆ er_95     │
│          ┆           ┆ f64       ┆           ┆   ┆ g         ┆ ---       ┆ ---       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆ ---       ┆ f64       ┆ f64       ┆ f64       │
│          ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10002    ┆ 40.95     ┆ 0.0       ┆ 35.58     ┆ … ┆ 0.0       ┆ 1.0       ┆ 2.0       ┆ 41.0      │
│ 10003    ┆ 43.77     ┆ 0.0       ┆ 37.96     ┆ … ┆ 0.01      ┆ 1.0       ┆ 1.0       ┆ 30.0      │
│ 1001     ┆ 39.25     ┆ 3.16      ┆ 31.98     ┆ … ┆ 0.0       ┆ 1.0       ┆ 17.0      ┆ 43.0      │
│ 101002   ┆ 70.88     ┆ 0.0       ┆ 15.37     ┆ … ┆ 0.0       ┆ 1.0       ┆ 1.0       ┆ 13.0      │
│ 101005   ┆ 71.02     ┆ 0.0       ┆ 15.55     ┆ … ┆ 0.0       ┆ 1.0       ┆ 1.0       ┆ 18.0      │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
df.describe()

shape: (9, 50)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ gauge_id  ┆ sand_perc ┆ sand_perc ┆ … ┆ soil_dept ┆ soil_dept ┆ soil_dept ┆ soil_dep │
│ ---       ┆ ---       ┆ ---       ┆ _missing  ┆   ┆ h_pelleti ┆ h_pelleti ┆ h_pelleti ┆ th_pelle │
│ str       ┆ f64       ┆ f64       ┆ ---       ┆   ┆ er_missin ┆ er_5      ┆ er_50     ┆ tier_95  │
│           ┆           ┆           ┆ f64       ┆   ┆ g         ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ f64       ┆ f64       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 671.0     ┆ 671.0     ┆ 671.0     ┆ … ┆ 671.0     ┆ 671.0     ┆ 671.0     ┆ 671.0    │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 43768.396 ┆ 45.376349 ┆ 1.016751  ┆ … ┆ 0.470656  ┆ 0.922504  ┆ NaN       ┆ NaN      │
│           ┆ 423       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 21894.720 ┆ 10.514986 ┆ 2.869213  ┆ … ┆ 3.126028  ┆ 0.939967  ┆ NaN       ┆ NaN      │
│           ┆ 374       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 1001.0    ┆ 19.37     ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 1.0       ┆ 1.0      │
│ 25%       ┆ 28015.0   ┆ 39.63     ┆ 0.0       ┆ … ┆ 0.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ 50%       ┆ 39127.0   ┆ 43.38     ┆ 0.0       ┆ … ┆ 0.0       ┆ 1.0       ┆ 1.0       ┆ 2.0      │
│ 75%       ┆ 56002.0   ┆ 50.35     ┆ 0.37      ┆ … ┆ 0.0       ┆ 1.0       ┆ 1.0       ┆ 24.0     │
│ max       ┆ 107001.0  ┆ 82.14     ┆ 30.53     ┆ … ┆ 50.97     ┆ 17.0      ┆ 50.0      ┆ 50.0     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
df.null_count()

shape: (1, 49)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ gauge_id ┆ sand_perc ┆ sand_perc ┆ silt_perc ┆ … ┆ soil_dept ┆ soil_dept ┆ soil_dept ┆ soil_dept │
│ ---      ┆ ---       ┆ _missing  ┆ ---       ┆   ┆ h_pelleti ┆ h_pelleti ┆ h_pelleti ┆ h_pelleti │
│ u32      ┆ u32       ┆ ---       ┆ u32       ┆   ┆ er_missin ┆ er_5      ┆ er_50     ┆ er_95     │
│          ┆           ┆ u32       ┆           ┆   ┆ g         ┆ ---       ┆ ---       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆ ---       ┆ u32       ┆ u32       ┆ u32       │
│          ┆           ┆           ┆           ┆   ┆ u32       ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [6]:
(df.null_count() / len(df) * 100).transpose()

shape: (49, 1)
┌──────────┐
│ column_0 │
│ ---      │
│ f64      │
╞══════════╡
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ …        │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
└──────────┘